<?php

use Illuminate\Database\Seeder;

class ContactCityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //Table reset
        DB::table("city")->delete();
        DB::table("city")->insert([ "id" => 1, "code" => "CITY001", "name" => "Badung", "displayname" => "Badung", "description" => "Badung", "numsort" => 10, "status" => 1, ]); 
        DB::table("city")->insert([ "id" => 2, "code" => "CITY002", "name" => "Bangli", "displayname" => "Bangli", "description" => "Bangli", "numsort" => 20, "status" => 2, ]); 
        DB::table("city")->insert([ "id" => 3, "code" => "CITY003", "name" => "Buleleng", "displayname" => "Buleleng", "description" => "Buleleng", "numsort" => 30, "status" => 3, ]); 
        DB::table("city")->insert([ "id" => 4, "code" => "CITY004", "name" => "Denpasar", "displayname" => "Denpasar", "description" => "Denpasar", "numsort" => 40, "status" => 4, ]); 
        DB::table("city")->insert([ "id" => 5, "code" => "CITY005", "name" => "Gianyar", "displayname" => "Gianyar", "description" => "Gianyar", "numsort" => 50, "status" => 5, ]); 
        DB::table("city")->insert([ "id" => 6, "code" => "CITY006", "name" => "Jembrana", "displayname" => "Jembrana", "description" => "Jembrana", "numsort" => 60, "status" => 6, ]); 
        DB::table("city")->insert([ "id" => 7, "code" => "CITY007", "name" => "Karangasem", "displayname" => "Karangasem", "description" => "Karangasem", "numsort" => 70, "status" => 7, ]); 
        DB::table("city")->insert([ "id" => 8, "code" => "CITY008", "name" => "Klungkung", "displayname" => "Klungkung", "description" => "Klungkung", "numsort" => 80, "status" => 8, ]); 
        DB::table("city")->insert([ "id" => 9, "code" => "CITY009", "name" => "Tabanan", "displayname" => "Tabanan", "description" => "Tabanan", "numsort" => 90, "status" => 9, ]); 
        DB::table("city")->insert([ "id" => 10, "code" => "CITY010", "name" => "Bangka", "displayname" => "Bangka", "description" => "Bangka", "numsort" => 100, "status" => 10, ]); 
        DB::table("city")->insert([ "id" => 11, "code" => "CITY011", "name" => "Bangka Barat", "displayname" => "Bangka Barat", "description" => "Bangka Barat", "numsort" => 110, "status" => 11, ]); 
        DB::table("city")->insert([ "id" => 12, "code" => "CITY012", "name" => "Bangka Selatan", "displayname" => "Bangka Selatan", "description" => "Bangka Selatan", "numsort" => 120, "status" => 12, ]); 
        DB::table("city")->insert([ "id" => 13, "code" => "CITY013", "name" => "Bangka Tengah", "displayname" => "Bangka Tengah", "description" => "Bangka Tengah", "numsort" => 130, "status" => 13, ]); 
        DB::table("city")->insert([ "id" => 14, "code" => "CITY014", "name" => "Belitung", "displayname" => "Belitung", "description" => "Belitung", "numsort" => 140, "status" => 14, ]); 
        DB::table("city")->insert([ "id" => 15, "code" => "CITY015", "name" => "Belitung Timur", "displayname" => "Belitung Timur", "description" => "Belitung Timur", "numsort" => 150, "status" => 15, ]); 
        DB::table("city")->insert([ "id" => 16, "code" => "CITY016", "name" => "Pangkal Pinang", "displayname" => "Pangkal Pinang", "description" => "Pangkal Pinang", "numsort" => 160, "status" => 16, ]); 
        DB::table("city")->insert([ "id" => 17, "code" => "CITY017", "name" => "Cilegon", "displayname" => "Cilegon", "description" => "Cilegon", "numsort" => 170, "status" => 17, ]); 
        DB::table("city")->insert([ "id" => 18, "code" => "CITY018", "name" => "Lebak", "displayname" => "Lebak", "description" => "Lebak", "numsort" => 180, "status" => 18, ]); 
        DB::table("city")->insert([ "id" => 19, "code" => "CITY019", "name" => "Pandeglang", "displayname" => "Pandeglang", "description" => "Pandeglang", "numsort" => 190, "status" => 19, ]); 
        DB::table("city")->insert([ "id" => 20, "code" => "CITY020", "name" => "Serang", "displayname" => "Serang", "description" => "Serang", "numsort" => 200, "status" => 20, ]); 
        DB::table("city")->insert([ "id" => 21, "code" => "CITY021", "name" => "Serang", "displayname" => "Serang", "description" => "Serang", "numsort" => 210, "status" => 21, ]); 
        DB::table("city")->insert([ "id" => 22, "code" => "CITY022", "name" => "Tangerang", "displayname" => "Tangerang", "description" => "Tangerang", "numsort" => 220, "status" => 22, ]); 
        DB::table("city")->insert([ "id" => 23, "code" => "CITY023", "name" => "Tangerang", "displayname" => "Tangerang", "description" => "Tangerang", "numsort" => 230, "status" => 23, ]); 
        DB::table("city")->insert([ "id" => 24, "code" => "CITY024", "name" => "Tangerang Selatan", "displayname" => "Tangerang Selatan", "description" => "Tangerang Selatan", "numsort" => 240, "status" => 24, ]); 
        DB::table("city")->insert([ "id" => 25, "code" => "CITY025", "name" => "Bengkulu", "displayname" => "Bengkulu", "description" => "Bengkulu", "numsort" => 250, "status" => 25, ]); 
        DB::table("city")->insert([ "id" => 26, "code" => "CITY026", "name" => "Bengkulu Selatan", "displayname" => "Bengkulu Selatan", "description" => "Bengkulu Selatan", "numsort" => 260, "status" => 26, ]); 
        DB::table("city")->insert([ "id" => 27, "code" => "CITY027", "name" => "Bengkulu Tengah", "displayname" => "Bengkulu Tengah", "description" => "Bengkulu Tengah", "numsort" => 270, "status" => 27, ]); 
        DB::table("city")->insert([ "id" => 28, "code" => "CITY028", "name" => "Bengkulu Utara", "displayname" => "Bengkulu Utara", "description" => "Bengkulu Utara", "numsort" => 280, "status" => 28, ]); 
        DB::table("city")->insert([ "id" => 29, "code" => "CITY029", "name" => "Kaur", "displayname" => "Kaur", "description" => "Kaur", "numsort" => 290, "status" => 29, ]); 
        DB::table("city")->insert([ "id" => 30, "code" => "CITY030", "name" => "Kepahiang", "displayname" => "Kepahiang", "description" => "Kepahiang", "numsort" => 300, "status" => 30, ]); 
        DB::table("city")->insert([ "id" => 31, "code" => "CITY031", "name" => "Lebong", "displayname" => "Lebong", "description" => "Lebong", "numsort" => 310, "status" => 31, ]); 
        DB::table("city")->insert([ "id" => 32, "code" => "CITY032", "name" => "Muko Muko", "displayname" => "Muko Muko", "description" => "Muko Muko", "numsort" => 320, "status" => 32, ]); 
        DB::table("city")->insert([ "id" => 33, "code" => "CITY033", "name" => "Rejang Lebong", "displayname" => "Rejang Lebong", "description" => "Rejang Lebong", "numsort" => 330, "status" => 33, ]); 
        DB::table("city")->insert([ "id" => 34, "code" => "CITY034", "name" => "Seluma", "displayname" => "Seluma", "description" => "Seluma", "numsort" => 340, "status" => 34, ]); 
        DB::table("city")->insert([ "id" => 35, "code" => "CITY035", "name" => "Bantul", "displayname" => "Bantul", "description" => "Bantul", "numsort" => 350, "status" => 35, ]); 
        DB::table("city")->insert([ "id" => 36, "code" => "CITY036", "name" => "Gunung Kidul", "displayname" => "Gunung Kidul", "description" => "Gunung Kidul", "numsort" => 360, "status" => 36, ]); 
        DB::table("city")->insert([ "id" => 37, "code" => "CITY037", "name" => "Kulon Progo", "displayname" => "Kulon Progo", "description" => "Kulon Progo", "numsort" => 370, "status" => 37, ]); 
        DB::table("city")->insert([ "id" => 38, "code" => "CITY038", "name" => "Sleman", "displayname" => "Sleman", "description" => "Sleman", "numsort" => 380, "status" => 38, ]); 
        DB::table("city")->insert([ "id" => 39, "code" => "CITY039", "name" => "Yogyakarta", "displayname" => "Yogyakarta", "description" => "Yogyakarta", "numsort" => 390, "status" => 39, ]); 
        DB::table("city")->insert([ "id" => 40, "code" => "CITY040", "name" => "Jakarta Barat", "displayname" => "Jakarta Barat", "description" => "Jakarta Barat", "numsort" => 400, "status" => 40, ]); 
        DB::table("city")->insert([ "id" => 41, "code" => "CITY041", "name" => "Jakarta Pusat", "displayname" => "Jakarta Pusat", "description" => "Jakarta Pusat", "numsort" => 410, "status" => 41, ]); 
        DB::table("city")->insert([ "id" => 42, "code" => "CITY042", "name" => "Jakarta Selatan", "displayname" => "Jakarta Selatan", "description" => "Jakarta Selatan", "numsort" => 420, "status" => 42, ]); 
        DB::table("city")->insert([ "id" => 43, "code" => "CITY043", "name" => "Jakarta Timur", "displayname" => "Jakarta Timur", "description" => "Jakarta Timur", "numsort" => 430, "status" => 43, ]); 
        DB::table("city")->insert([ "id" => 44, "code" => "CITY044", "name" => "Jakarta Utara", "displayname" => "Jakarta Utara", "description" => "Jakarta Utara", "numsort" => 440, "status" => 44, ]); 
        DB::table("city")->insert([ "id" => 45, "code" => "CITY045", "name" => "Kepulauan Seribu", "displayname" => "Kepulauan Seribu", "description" => "Kepulauan Seribu", "numsort" => 450, "status" => 45, ]); 
        DB::table("city")->insert([ "id" => 46, "code" => "CITY046", "name" => "Boalemo", "displayname" => "Boalemo", "description" => "Boalemo", "numsort" => 460, "status" => 46, ]); 
        DB::table("city")->insert([ "id" => 47, "code" => "CITY047", "name" => "Bone Bolango", "displayname" => "Bone Bolango", "description" => "Bone Bolango", "numsort" => 470, "status" => 47, ]); 
        DB::table("city")->insert([ "id" => 48, "code" => "CITY048", "name" => "Gorontalo", "displayname" => "Gorontalo", "description" => "Gorontalo", "numsort" => 480, "status" => 48, ]); 
        DB::table("city")->insert([ "id" => 49, "code" => "CITY049", "name" => "Gorontalo", "displayname" => "Gorontalo", "description" => "Gorontalo", "numsort" => 490, "status" => 49, ]); 
        DB::table("city")->insert([ "id" => 50, "code" => "CITY050", "name" => "Gorontalo Utara", "displayname" => "Gorontalo Utara", "description" => "Gorontalo Utara", "numsort" => 500, "status" => 50, ]); 
        DB::table("city")->insert([ "id" => 51, "code" => "CITY051", "name" => "Pohuwato", "displayname" => "Pohuwato", "description" => "Pohuwato", "numsort" => 510, "status" => 51, ]); 
        DB::table("city")->insert([ "id" => 52, "code" => "CITY052", "name" => "Batang Hari", "displayname" => "Batang Hari", "description" => "Batang Hari", "numsort" => 520, "status" => 52, ]); 
        DB::table("city")->insert([ "id" => 53, "code" => "CITY053", "name" => "Bungo", "displayname" => "Bungo", "description" => "Bungo", "numsort" => 530, "status" => 53, ]); 
        DB::table("city")->insert([ "id" => 54, "code" => "CITY054", "name" => "Jambi", "displayname" => "Jambi", "description" => "Jambi", "numsort" => 540, "status" => 54, ]); 
        DB::table("city")->insert([ "id" => 55, "code" => "CITY055", "name" => "Kerinci", "displayname" => "Kerinci", "description" => "Kerinci", "numsort" => 550, "status" => 55, ]); 
        DB::table("city")->insert([ "id" => 56, "code" => "CITY056", "name" => "Merangin", "displayname" => "Merangin", "description" => "Merangin", "numsort" => 560, "status" => 56, ]); 
        DB::table("city")->insert([ "id" => 57, "code" => "CITY057", "name" => "Muaro Jambi", "displayname" => "Muaro Jambi", "description" => "Muaro Jambi", "numsort" => 570, "status" => 57, ]); 
        DB::table("city")->insert([ "id" => 58, "code" => "CITY058", "name" => "Sarolangun", "displayname" => "Sarolangun", "description" => "Sarolangun", "numsort" => 580, "status" => 58, ]); 
        DB::table("city")->insert([ "id" => 59, "code" => "CITY059", "name" => "Sungaipenuh", "displayname" => "Sungaipenuh", "description" => "Sungaipenuh", "numsort" => 590, "status" => 59, ]); 
        DB::table("city")->insert([ "id" => 60, "code" => "CITY060", "name" => "Tanjung Jabung Barat", "displayname" => "Tanjung Jabung Barat", "description" => "Tanjung Jabung Barat", "numsort" => 600, "status" => 60, ]); 
        DB::table("city")->insert([ "id" => 61, "code" => "CITY061", "name" => "Tanjung Jabung Timur", "displayname" => "Tanjung Jabung Timur", "description" => "Tanjung Jabung Timur", "numsort" => 610, "status" => 61, ]); 
        DB::table("city")->insert([ "id" => 62, "code" => "CITY062", "name" => "Tebo", "displayname" => "Tebo", "description" => "Tebo", "numsort" => 620, "status" => 62, ]); 
        DB::table("city")->insert([ "id" => 63, "code" => "CITY063", "name" => "Bandung", "displayname" => "Bandung", "description" => "Bandung", "numsort" => 630, "status" => 63, ]); 
        DB::table("city")->insert([ "id" => 64, "code" => "CITY064", "name" => "Bandung", "displayname" => "Bandung", "description" => "Bandung", "numsort" => 640, "status" => 64, ]); 
        DB::table("city")->insert([ "id" => 65, "code" => "CITY065", "name" => "Bandung Barat", "displayname" => "Bandung Barat", "description" => "Bandung Barat", "numsort" => 650, "status" => 65, ]); 
        DB::table("city")->insert([ "id" => 66, "code" => "CITY066", "name" => "Banjar", "displayname" => "Banjar", "description" => "Banjar", "numsort" => 660, "status" => 66, ]); 
        DB::table("city")->insert([ "id" => 67, "code" => "CITY067", "name" => "Bekasi", "displayname" => "Bekasi", "description" => "Bekasi", "numsort" => 670, "status" => 67, ]); 
        DB::table("city")->insert([ "id" => 68, "code" => "CITY068", "name" => "Bekasi", "displayname" => "Bekasi", "description" => "Bekasi", "numsort" => 680, "status" => 68, ]); 
        DB::table("city")->insert([ "id" => 69, "code" => "CITY069", "name" => "Bogor", "displayname" => "Bogor", "description" => "Bogor", "numsort" => 690, "status" => 69, ]); 
        DB::table("city")->insert([ "id" => 70, "code" => "CITY070", "name" => "Bogor", "displayname" => "Bogor", "description" => "Bogor", "numsort" => 700, "status" => 70, ]); 
        DB::table("city")->insert([ "id" => 71, "code" => "CITY071", "name" => "Ciamis", "displayname" => "Ciamis", "description" => "Ciamis", "numsort" => 710, "status" => 71, ]); 
        DB::table("city")->insert([ "id" => 72, "code" => "CITY072", "name" => "Cianjur", "displayname" => "Cianjur", "description" => "Cianjur", "numsort" => 720, "status" => 72, ]); 
        DB::table("city")->insert([ "id" => 73, "code" => "CITY073", "name" => "Cimahi", "displayname" => "Cimahi", "description" => "Cimahi", "numsort" => 730, "status" => 73, ]); 
        DB::table("city")->insert([ "id" => 74, "code" => "CITY074", "name" => "Cirebon", "displayname" => "Cirebon", "description" => "Cirebon", "numsort" => 740, "status" => 74, ]); 
        DB::table("city")->insert([ "id" => 75, "code" => "CITY075", "name" => "Cirebon", "displayname" => "Cirebon", "description" => "Cirebon", "numsort" => 750, "status" => 75, ]); 
        DB::table("city")->insert([ "id" => 76, "code" => "CITY076", "name" => "Depok", "displayname" => "Depok", "description" => "Depok", "numsort" => 760, "status" => 76, ]); 
        DB::table("city")->insert([ "id" => 77, "code" => "CITY077", "name" => "Garut", "displayname" => "Garut", "description" => "Garut", "numsort" => 770, "status" => 77, ]); 
        DB::table("city")->insert([ "id" => 78, "code" => "CITY078", "name" => "Indramayu", "displayname" => "Indramayu", "description" => "Indramayu", "numsort" => 780, "status" => 78, ]); 
        DB::table("city")->insert([ "id" => 79, "code" => "CITY079", "name" => "Karawang", "displayname" => "Karawang", "description" => "Karawang", "numsort" => 790, "status" => 79, ]); 
        DB::table("city")->insert([ "id" => 80, "code" => "CITY080", "name" => "Kuningan", "displayname" => "Kuningan", "description" => "Kuningan", "numsort" => 800, "status" => 80, ]); 
        DB::table("city")->insert([ "id" => 81, "code" => "CITY081", "name" => "Majalengka", "displayname" => "Majalengka", "description" => "Majalengka", "numsort" => 810, "status" => 81, ]); 
        DB::table("city")->insert([ "id" => 82, "code" => "CITY082", "name" => "Purwakarta", "displayname" => "Purwakarta", "description" => "Purwakarta", "numsort" => 820, "status" => 82, ]); 
        DB::table("city")->insert([ "id" => 83, "code" => "CITY083", "name" => "Subang", "displayname" => "Subang", "description" => "Subang", "numsort" => 830, "status" => 83, ]); 
        DB::table("city")->insert([ "id" => 84, "code" => "CITY084", "name" => "Sukabumi", "displayname" => "Sukabumi", "description" => "Sukabumi", "numsort" => 840, "status" => 84, ]); 
        DB::table("city")->insert([ "id" => 85, "code" => "CITY085", "name" => "Sukabumi", "displayname" => "Sukabumi", "description" => "Sukabumi", "numsort" => 850, "status" => 85, ]); 
        DB::table("city")->insert([ "id" => 86, "code" => "CITY086", "name" => "Sumedang", "displayname" => "Sumedang", "description" => "Sumedang", "numsort" => 860, "status" => 86, ]); 
        DB::table("city")->insert([ "id" => 87, "code" => "CITY087", "name" => "Tasikmalaya", "displayname" => "Tasikmalaya", "description" => "Tasikmalaya", "numsort" => 870, "status" => 87, ]); 
        DB::table("city")->insert([ "id" => 88, "code" => "CITY088", "name" => "Tasikmalaya", "displayname" => "Tasikmalaya", "description" => "Tasikmalaya", "numsort" => 880, "status" => 88, ]); 
        DB::table("city")->insert([ "id" => 89, "code" => "CITY089", "name" => "Banjarnegara", "displayname" => "Banjarnegara", "description" => "Banjarnegara", "numsort" => 890, "status" => 89, ]); 
        DB::table("city")->insert([ "id" => 90, "code" => "CITY090", "name" => "Banyumas", "displayname" => "Banyumas", "description" => "Banyumas", "numsort" => 900, "status" => 90, ]); 
        DB::table("city")->insert([ "id" => 91, "code" => "CITY091", "name" => "Batang", "displayname" => "Batang", "description" => "Batang", "numsort" => 910, "status" => 91, ]); 
        DB::table("city")->insert([ "id" => 92, "code" => "CITY092", "name" => "Blora", "displayname" => "Blora", "description" => "Blora", "numsort" => 920, "status" => 92, ]); 
        DB::table("city")->insert([ "id" => 93, "code" => "CITY093", "name" => "Boyolali", "displayname" => "Boyolali", "description" => "Boyolali", "numsort" => 930, "status" => 93, ]); 
        DB::table("city")->insert([ "id" => 94, "code" => "CITY094", "name" => "Brebes", "displayname" => "Brebes", "description" => "Brebes", "numsort" => 940, "status" => 94, ]); 
        DB::table("city")->insert([ "id" => 95, "code" => "CITY095", "name" => "Cilacap", "displayname" => "Cilacap", "description" => "Cilacap", "numsort" => 950, "status" => 95, ]); 
        DB::table("city")->insert([ "id" => 96, "code" => "CITY096", "name" => "Demak", "displayname" => "Demak", "description" => "Demak", "numsort" => 960, "status" => 96, ]); 
        DB::table("city")->insert([ "id" => 97, "code" => "CITY097", "name" => "Grobogan", "displayname" => "Grobogan", "description" => "Grobogan", "numsort" => 970, "status" => 97, ]); 
        DB::table("city")->insert([ "id" => 98, "code" => "CITY098", "name" => "Jepara", "displayname" => "Jepara", "description" => "Jepara", "numsort" => 980, "status" => 98, ]); 
        DB::table("city")->insert([ "id" => 99, "code" => "CITY099", "name" => "Karanganyar", "displayname" => "Karanganyar", "description" => "Karanganyar", "numsort" => 990, "status" => 99, ]); 
        DB::table("city")->insert([ "id" => 100, "code" => "CITY100", "name" => "Kebumen", "displayname" => "Kebumen", "description" => "Kebumen", "numsort" => 1000, "status" => 100, ]); 
        DB::table("city")->insert([ "id" => 101, "code" => "CITY101", "name" => "Kendal", "displayname" => "Kendal", "description" => "Kendal", "numsort" => 1010, "status" => 101, ]); 
        DB::table("city")->insert([ "id" => 102, "code" => "CITY102", "name" => "Klaten", "displayname" => "Klaten", "description" => "Klaten", "numsort" => 1020, "status" => 102, ]); 
        DB::table("city")->insert([ "id" => 103, "code" => "CITY103", "name" => "Kudus", "displayname" => "Kudus", "description" => "Kudus", "numsort" => 1030, "status" => 103, ]); 
        DB::table("city")->insert([ "id" => 104, "code" => "CITY104", "name" => "Magelang", "displayname" => "Magelang", "description" => "Magelang", "numsort" => 1040, "status" => 104, ]); 
        DB::table("city")->insert([ "id" => 105, "code" => "CITY105", "name" => "Magelang", "displayname" => "Magelang", "description" => "Magelang", "numsort" => 1050, "status" => 105, ]); 
        DB::table("city")->insert([ "id" => 106, "code" => "CITY106", "name" => "Pati", "displayname" => "Pati", "description" => "Pati", "numsort" => 1060, "status" => 106, ]); 
        DB::table("city")->insert([ "id" => 107, "code" => "CITY107", "name" => "Pekalongan", "displayname" => "Pekalongan", "description" => "Pekalongan", "numsort" => 1070, "status" => 107, ]); 
        DB::table("city")->insert([ "id" => 108, "code" => "CITY108", "name" => "Pekalongan", "displayname" => "Pekalongan", "description" => "Pekalongan", "numsort" => 1080, "status" => 108, ]); 
        DB::table("city")->insert([ "id" => 109, "code" => "CITY109", "name" => "Pemalang", "displayname" => "Pemalang", "description" => "Pemalang", "numsort" => 1090, "status" => 109, ]); 
        DB::table("city")->insert([ "id" => 110, "code" => "CITY110", "name" => "Purbalingga", "displayname" => "Purbalingga", "description" => "Purbalingga", "numsort" => 1100, "status" => 110, ]); 
        DB::table("city")->insert([ "id" => 111, "code" => "CITY111", "name" => "Purworejo", "displayname" => "Purworejo", "description" => "Purworejo", "numsort" => 1110, "status" => 111, ]); 
        DB::table("city")->insert([ "id" => 112, "code" => "CITY112", "name" => "Rembang", "displayname" => "Rembang", "description" => "Rembang", "numsort" => 1120, "status" => 112, ]); 
        DB::table("city")->insert([ "id" => 113, "code" => "CITY113", "name" => "Salatiga", "displayname" => "Salatiga", "description" => "Salatiga", "numsort" => 1130, "status" => 113, ]); 
        DB::table("city")->insert([ "id" => 114, "code" => "CITY114", "name" => "Semarang", "displayname" => "Semarang", "description" => "Semarang", "numsort" => 1140, "status" => 114, ]); 
        DB::table("city")->insert([ "id" => 115, "code" => "CITY115", "name" => "Semarang", "displayname" => "Semarang", "description" => "Semarang", "numsort" => 1150, "status" => 115, ]); 
        DB::table("city")->insert([ "id" => 116, "code" => "CITY116", "name" => "Sragen", "displayname" => "Sragen", "description" => "Sragen", "numsort" => 1160, "status" => 116, ]); 
        DB::table("city")->insert([ "id" => 117, "code" => "CITY117", "name" => "Sukoharjo", "displayname" => "Sukoharjo", "description" => "Sukoharjo", "numsort" => 1170, "status" => 117, ]); 
        DB::table("city")->insert([ "id" => 118, "code" => "CITY118", "name" => "Surakarta (Solo)", "displayname" => "Surakarta (Solo)", "description" => "Surakarta (Solo)", "numsort" => 1180, "status" => 118, ]); 
        DB::table("city")->insert([ "id" => 119, "code" => "CITY119", "name" => "Tegal", "displayname" => "Tegal", "description" => "Tegal", "numsort" => 1190, "status" => 119, ]); 
        DB::table("city")->insert([ "id" => 120, "code" => "CITY120", "name" => "Tegal", "displayname" => "Tegal", "description" => "Tegal", "numsort" => 1200, "status" => 120, ]); 
        DB::table("city")->insert([ "id" => 121, "code" => "CITY121", "name" => "Temanggung", "displayname" => "Temanggung", "description" => "Temanggung", "numsort" => 1210, "status" => 121, ]); 
        DB::table("city")->insert([ "id" => 122, "code" => "CITY122", "name" => "Wonogiri", "displayname" => "Wonogiri", "description" => "Wonogiri", "numsort" => 1220, "status" => 122, ]); 
        DB::table("city")->insert([ "id" => 123, "code" => "CITY123", "name" => "Wonosobo", "displayname" => "Wonosobo", "description" => "Wonosobo", "numsort" => 1230, "status" => 123, ]); 
        DB::table("city")->insert([ "id" => 124, "code" => "CITY124", "name" => "Bangkalan", "displayname" => "Bangkalan", "description" => "Bangkalan", "numsort" => 1240, "status" => 124, ]); 
        DB::table("city")->insert([ "id" => 125, "code" => "CITY125", "name" => "Banyuwangi", "displayname" => "Banyuwangi", "description" => "Banyuwangi", "numsort" => 1250, "status" => 125, ]); 
        DB::table("city")->insert([ "id" => 126, "code" => "CITY126", "name" => "Batu", "displayname" => "Batu", "description" => "Batu", "numsort" => 1260, "status" => 126, ]); 
        DB::table("city")->insert([ "id" => 127, "code" => "CITY127", "name" => "Blitar", "displayname" => "Blitar", "description" => "Blitar", "numsort" => 1270, "status" => 127, ]); 
        DB::table("city")->insert([ "id" => 128, "code" => "CITY128", "name" => "Blitar", "displayname" => "Blitar", "description" => "Blitar", "numsort" => 1280, "status" => 128, ]); 
        DB::table("city")->insert([ "id" => 129, "code" => "CITY129", "name" => "Bojonegoro", "displayname" => "Bojonegoro", "description" => "Bojonegoro", "numsort" => 1290, "status" => 129, ]); 
        DB::table("city")->insert([ "id" => 130, "code" => "CITY130", "name" => "Bondowoso", "displayname" => "Bondowoso", "description" => "Bondowoso", "numsort" => 1300, "status" => 130, ]); 
        DB::table("city")->insert([ "id" => 131, "code" => "CITY131", "name" => "Gresik", "displayname" => "Gresik", "description" => "Gresik", "numsort" => 1310, "status" => 131, ]); 
        DB::table("city")->insert([ "id" => 132, "code" => "CITY132", "name" => "Jember", "displayname" => "Jember", "description" => "Jember", "numsort" => 1320, "status" => 132, ]); 
        DB::table("city")->insert([ "id" => 133, "code" => "CITY133", "name" => "Jombang", "displayname" => "Jombang", "description" => "Jombang", "numsort" => 1330, "status" => 133, ]); 
        DB::table("city")->insert([ "id" => 134, "code" => "CITY134", "name" => "Kediri", "displayname" => "Kediri", "description" => "Kediri", "numsort" => 1340, "status" => 134, ]); 
        DB::table("city")->insert([ "id" => 135, "code" => "CITY135", "name" => "Kediri", "displayname" => "Kediri", "description" => "Kediri", "numsort" => 1350, "status" => 135, ]); 
        DB::table("city")->insert([ "id" => 136, "code" => "CITY136", "name" => "Lamongan", "displayname" => "Lamongan", "description" => "Lamongan", "numsort" => 1360, "status" => 136, ]); 
        DB::table("city")->insert([ "id" => 137, "code" => "CITY137", "name" => "Lumajang", "displayname" => "Lumajang", "description" => "Lumajang", "numsort" => 1370, "status" => 137, ]); 
        DB::table("city")->insert([ "id" => 138, "code" => "CITY138", "name" => "Madiun", "displayname" => "Madiun", "description" => "Madiun", "numsort" => 1380, "status" => 138, ]); 
        DB::table("city")->insert([ "id" => 139, "code" => "CITY139", "name" => "Madiun", "displayname" => "Madiun", "description" => "Madiun", "numsort" => 1390, "status" => 139, ]); 
        DB::table("city")->insert([ "id" => 140, "code" => "CITY140", "name" => "Magetan", "displayname" => "Magetan", "description" => "Magetan", "numsort" => 1400, "status" => 140, ]); 
        DB::table("city")->insert([ "id" => 141, "code" => "CITY141", "name" => "Malang", "displayname" => "Malang", "description" => "Malang", "numsort" => 1410, "status" => 141, ]); 
        DB::table("city")->insert([ "id" => 142, "code" => "CITY142", "name" => "Malang", "displayname" => "Malang", "description" => "Malang", "numsort" => 1420, "status" => 142, ]); 
        DB::table("city")->insert([ "id" => 143, "code" => "CITY143", "name" => "Mojokerto", "displayname" => "Mojokerto", "description" => "Mojokerto", "numsort" => 1430, "status" => 143, ]); 
        DB::table("city")->insert([ "id" => 144, "code" => "CITY144", "name" => "Mojokerto", "displayname" => "Mojokerto", "description" => "Mojokerto", "numsort" => 1440, "status" => 144, ]); 
        DB::table("city")->insert([ "id" => 145, "code" => "CITY145", "name" => "Nganjuk", "displayname" => "Nganjuk", "description" => "Nganjuk", "numsort" => 1450, "status" => 145, ]); 
        DB::table("city")->insert([ "id" => 146, "code" => "CITY146", "name" => "Ngawi", "displayname" => "Ngawi", "description" => "Ngawi", "numsort" => 1460, "status" => 146, ]); 
        DB::table("city")->insert([ "id" => 147, "code" => "CITY147", "name" => "Pacitan", "displayname" => "Pacitan", "description" => "Pacitan", "numsort" => 1470, "status" => 147, ]); 
        DB::table("city")->insert([ "id" => 148, "code" => "CITY148", "name" => "Pamekasan", "displayname" => "Pamekasan", "description" => "Pamekasan", "numsort" => 1480, "status" => 148, ]); 
        DB::table("city")->insert([ "id" => 149, "code" => "CITY149", "name" => "Pasuruan", "displayname" => "Pasuruan", "description" => "Pasuruan", "numsort" => 1490, "status" => 149, ]); 
        DB::table("city")->insert([ "id" => 150, "code" => "CITY150", "name" => "Pasuruan", "displayname" => "Pasuruan", "description" => "Pasuruan", "numsort" => 1500, "status" => 150, ]); 
        DB::table("city")->insert([ "id" => 151, "code" => "CITY151", "name" => "Ponorogo", "displayname" => "Ponorogo", "description" => "Ponorogo", "numsort" => 1510, "status" => 151, ]); 
        DB::table("city")->insert([ "id" => 152, "code" => "CITY152", "name" => "Probolinggo", "displayname" => "Probolinggo", "description" => "Probolinggo", "numsort" => 1520, "status" => 152, ]); 
        DB::table("city")->insert([ "id" => 153, "code" => "CITY153", "name" => "Probolinggo", "displayname" => "Probolinggo", "description" => "Probolinggo", "numsort" => 1530, "status" => 153, ]); 
        DB::table("city")->insert([ "id" => 154, "code" => "CITY154", "name" => "Sampang", "displayname" => "Sampang", "description" => "Sampang", "numsort" => 1540, "status" => 154, ]); 
        DB::table("city")->insert([ "id" => 155, "code" => "CITY155", "name" => "Sidoarjo", "displayname" => "Sidoarjo", "description" => "Sidoarjo", "numsort" => 1550, "status" => 155, ]); 
        DB::table("city")->insert([ "id" => 156, "code" => "CITY156", "name" => "Situbondo", "displayname" => "Situbondo", "description" => "Situbondo", "numsort" => 1560, "status" => 156, ]); 
        DB::table("city")->insert([ "id" => 157, "code" => "CITY157", "name" => "Sumenep", "displayname" => "Sumenep", "description" => "Sumenep", "numsort" => 1570, "status" => 157, ]); 
        DB::table("city")->insert([ "id" => 158, "code" => "CITY158", "name" => "Surabaya", "displayname" => "Surabaya", "description" => "Surabaya", "numsort" => 1580, "status" => 158, ]); 
        DB::table("city")->insert([ "id" => 159, "code" => "CITY159", "name" => "Trenggalek", "displayname" => "Trenggalek", "description" => "Trenggalek", "numsort" => 1590, "status" => 159, ]); 
        DB::table("city")->insert([ "id" => 160, "code" => "CITY160", "name" => "Tuban", "displayname" => "Tuban", "description" => "Tuban", "numsort" => 1600, "status" => 160, ]); 
        DB::table("city")->insert([ "id" => 161, "code" => "CITY161", "name" => "Tulungagung", "displayname" => "Tulungagung", "description" => "Tulungagung", "numsort" => 1610, "status" => 161, ]); 
        DB::table("city")->insert([ "id" => 162, "code" => "CITY162", "name" => "Bengkayang", "displayname" => "Bengkayang", "description" => "Bengkayang", "numsort" => 1620, "status" => 162, ]); 
        DB::table("city")->insert([ "id" => 163, "code" => "CITY163", "name" => "Kapuas Hulu", "displayname" => "Kapuas Hulu", "description" => "Kapuas Hulu", "numsort" => 1630, "status" => 163, ]); 
        DB::table("city")->insert([ "id" => 164, "code" => "CITY164", "name" => "Kayong Utara", "displayname" => "Kayong Utara", "description" => "Kayong Utara", "numsort" => 1640, "status" => 164, ]); 
        DB::table("city")->insert([ "id" => 165, "code" => "CITY165", "name" => "Ketapang", "displayname" => "Ketapang", "description" => "Ketapang", "numsort" => 1650, "status" => 165, ]); 
        DB::table("city")->insert([ "id" => 166, "code" => "CITY166", "name" => "Kubu Raya", "displayname" => "Kubu Raya", "description" => "Kubu Raya", "numsort" => 1660, "status" => 166, ]); 
        DB::table("city")->insert([ "id" => 167, "code" => "CITY167", "name" => "Landak", "displayname" => "Landak", "description" => "Landak", "numsort" => 1670, "status" => 167, ]); 
        DB::table("city")->insert([ "id" => 168, "code" => "CITY168", "name" => "Melawi", "displayname" => "Melawi", "description" => "Melawi", "numsort" => 1680, "status" => 168, ]); 
        DB::table("city")->insert([ "id" => 169, "code" => "CITY169", "name" => "Pontianak", "displayname" => "Pontianak", "description" => "Pontianak", "numsort" => 1690, "status" => 169, ]); 
        DB::table("city")->insert([ "id" => 170, "code" => "CITY170", "name" => "Pontianak", "displayname" => "Pontianak", "description" => "Pontianak", "numsort" => 1700, "status" => 170, ]); 
        DB::table("city")->insert([ "id" => 171, "code" => "CITY171", "name" => "Sambas", "displayname" => "Sambas", "description" => "Sambas", "numsort" => 1710, "status" => 171, ]); 
        DB::table("city")->insert([ "id" => 172, "code" => "CITY172", "name" => "Sanggau", "displayname" => "Sanggau", "description" => "Sanggau", "numsort" => 1720, "status" => 172, ]); 
        DB::table("city")->insert([ "id" => 173, "code" => "CITY173", "name" => "Sekadau", "displayname" => "Sekadau", "description" => "Sekadau", "numsort" => 1730, "status" => 173, ]); 
        DB::table("city")->insert([ "id" => 174, "code" => "CITY174", "name" => "Singkawang", "displayname" => "Singkawang", "description" => "Singkawang", "numsort" => 1740, "status" => 174, ]); 
        DB::table("city")->insert([ "id" => 175, "code" => "CITY175", "name" => "Sintang", "displayname" => "Sintang", "description" => "Sintang", "numsort" => 1750, "status" => 175, ]); 
        DB::table("city")->insert([ "id" => 176, "code" => "CITY176", "name" => "Balangan", "displayname" => "Balangan", "description" => "Balangan", "numsort" => 1760, "status" => 176, ]); 
        DB::table("city")->insert([ "id" => 177, "code" => "CITY177", "name" => "Banjar", "displayname" => "Banjar", "description" => "Banjar", "numsort" => 1770, "status" => 177, ]); 
        DB::table("city")->insert([ "id" => 178, "code" => "CITY178", "name" => "Banjarbaru", "displayname" => "Banjarbaru", "description" => "Banjarbaru", "numsort" => 1780, "status" => 178, ]); 
        DB::table("city")->insert([ "id" => 179, "code" => "CITY179", "name" => "Banjarmasin", "displayname" => "Banjarmasin", "description" => "Banjarmasin", "numsort" => 1790, "status" => 179, ]); 
        DB::table("city")->insert([ "id" => 180, "code" => "CITY180", "name" => "Barito Kuala", "displayname" => "Barito Kuala", "description" => "Barito Kuala", "numsort" => 1800, "status" => 180, ]); 
        DB::table("city")->insert([ "id" => 181, "code" => "CITY181", "name" => "Hulu Sungai Selatan", "displayname" => "Hulu Sungai Selatan", "description" => "Hulu Sungai Selatan", "numsort" => 1810, "status" => 181, ]); 
        DB::table("city")->insert([ "id" => 182, "code" => "CITY182", "name" => "Hulu Sungai Tengah", "displayname" => "Hulu Sungai Tengah", "description" => "Hulu Sungai Tengah", "numsort" => 1820, "status" => 182, ]); 
        DB::table("city")->insert([ "id" => 183, "code" => "CITY183", "name" => "Hulu Sungai Utara", "displayname" => "Hulu Sungai Utara", "description" => "Hulu Sungai Utara", "numsort" => 1830, "status" => 183, ]); 
        DB::table("city")->insert([ "id" => 184, "code" => "CITY184", "name" => "Kotabaru", "displayname" => "Kotabaru", "description" => "Kotabaru", "numsort" => 1840, "status" => 184, ]); 
        DB::table("city")->insert([ "id" => 185, "code" => "CITY185", "name" => "Tabalong", "displayname" => "Tabalong", "description" => "Tabalong", "numsort" => 1850, "status" => 185, ]); 
        DB::table("city")->insert([ "id" => 186, "code" => "CITY186", "name" => "Tanah Bumbu", "displayname" => "Tanah Bumbu", "description" => "Tanah Bumbu", "numsort" => 1860, "status" => 186, ]); 
        DB::table("city")->insert([ "id" => 187, "code" => "CITY187", "name" => "Tanah Laut", "displayname" => "Tanah Laut", "description" => "Tanah Laut", "numsort" => 1870, "status" => 187, ]); 
        DB::table("city")->insert([ "id" => 188, "code" => "CITY188", "name" => "Tapin", "displayname" => "Tapin", "description" => "Tapin", "numsort" => 1880, "status" => 188, ]); 
        DB::table("city")->insert([ "id" => 189, "code" => "CITY189", "name" => "Barito Selatan", "displayname" => "Barito Selatan", "description" => "Barito Selatan", "numsort" => 1890, "status" => 189, ]); 
        DB::table("city")->insert([ "id" => 190, "code" => "CITY190", "name" => "Barito Timur", "displayname" => "Barito Timur", "description" => "Barito Timur", "numsort" => 1900, "status" => 190, ]); 
        DB::table("city")->insert([ "id" => 191, "code" => "CITY191", "name" => "Barito Utara", "displayname" => "Barito Utara", "description" => "Barito Utara", "numsort" => 1910, "status" => 191, ]); 
        DB::table("city")->insert([ "id" => 192, "code" => "CITY192", "name" => "Gunung Mas", "displayname" => "Gunung Mas", "description" => "Gunung Mas", "numsort" => 1920, "status" => 192, ]); 
        DB::table("city")->insert([ "id" => 193, "code" => "CITY193", "name" => "Kapuas", "displayname" => "Kapuas", "description" => "Kapuas", "numsort" => 1930, "status" => 193, ]); 
        DB::table("city")->insert([ "id" => 194, "code" => "CITY194", "name" => "Katingan", "displayname" => "Katingan", "description" => "Katingan", "numsort" => 1940, "status" => 194, ]); 
        DB::table("city")->insert([ "id" => 195, "code" => "CITY195", "name" => "Kotawaringin Barat", "displayname" => "Kotawaringin Barat", "description" => "Kotawaringin Barat", "numsort" => 1950, "status" => 195, ]); 
        DB::table("city")->insert([ "id" => 196, "code" => "CITY196", "name" => "Kotawaringin Timur", "displayname" => "Kotawaringin Timur", "description" => "Kotawaringin Timur", "numsort" => 1960, "status" => 196, ]); 
        DB::table("city")->insert([ "id" => 197, "code" => "CITY197", "name" => "Lamandau", "displayname" => "Lamandau", "description" => "Lamandau", "numsort" => 1970, "status" => 197, ]); 
        DB::table("city")->insert([ "id" => 198, "code" => "CITY198", "name" => "Murung Raya", "displayname" => "Murung Raya", "description" => "Murung Raya", "numsort" => 1980, "status" => 198, ]); 
        DB::table("city")->insert([ "id" => 199, "code" => "CITY199", "name" => "Palangka Raya", "displayname" => "Palangka Raya", "description" => "Palangka Raya", "numsort" => 1990, "status" => 199, ]); 
        DB::table("city")->insert([ "id" => 200, "code" => "CITY200", "name" => "Pulang Pisau", "displayname" => "Pulang Pisau", "description" => "Pulang Pisau", "numsort" => 2000, "status" => 200, ]); 
        DB::table("city")->insert([ "id" => 201, "code" => "CITY201", "name" => "Seruyan", "displayname" => "Seruyan", "description" => "Seruyan", "numsort" => 2010, "status" => 201, ]); 
        DB::table("city")->insert([ "id" => 202, "code" => "CITY202", "name" => "Sukamara", "displayname" => "Sukamara", "description" => "Sukamara", "numsort" => 2020, "status" => 202, ]); 
        DB::table("city")->insert([ "id" => 203, "code" => "CITY203", "name" => "Balikpapan", "displayname" => "Balikpapan", "description" => "Balikpapan", "numsort" => 2030, "status" => 203, ]); 
        DB::table("city")->insert([ "id" => 204, "code" => "CITY204", "name" => "Berau", "displayname" => "Berau", "description" => "Berau", "numsort" => 2040, "status" => 204, ]); 
        DB::table("city")->insert([ "id" => 205, "code" => "CITY205", "name" => "Bontang", "displayname" => "Bontang", "description" => "Bontang", "numsort" => 2050, "status" => 205, ]); 
        DB::table("city")->insert([ "id" => 206, "code" => "CITY206", "name" => "Bulungan (Bulongan)", "displayname" => "Bulungan (Bulongan)", "description" => "Bulungan (Bulongan)", "numsort" => 2060, "status" => 206, ]); 
        DB::table("city")->insert([ "id" => 207, "code" => "CITY207", "name" => "Kutai Barat", "displayname" => "Kutai Barat", "description" => "Kutai Barat", "numsort" => 2070, "status" => 207, ]); 
        DB::table("city")->insert([ "id" => 208, "code" => "CITY208", "name" => "Kutai Kartanegara", "displayname" => "Kutai Kartanegara", "description" => "Kutai Kartanegara", "numsort" => 2080, "status" => 208, ]); 
        DB::table("city")->insert([ "id" => 209, "code" => "CITY209", "name" => "Kutai Timur", "displayname" => "Kutai Timur", "description" => "Kutai Timur", "numsort" => 2090, "status" => 209, ]); 
        DB::table("city")->insert([ "id" => 210, "code" => "CITY210", "name" => "Malinau", "displayname" => "Malinau", "description" => "Malinau", "numsort" => 2100, "status" => 210, ]); 
        DB::table("city")->insert([ "id" => 211, "code" => "CITY211", "name" => "Nunukan", "displayname" => "Nunukan", "description" => "Nunukan", "numsort" => 2110, "status" => 211, ]); 
        DB::table("city")->insert([ "id" => 212, "code" => "CITY212", "name" => "Paser", "displayname" => "Paser", "description" => "Paser", "numsort" => 2120, "status" => 212, ]); 
        DB::table("city")->insert([ "id" => 213, "code" => "CITY213", "name" => "Penajam Paser Utara", "displayname" => "Penajam Paser Utara", "description" => "Penajam Paser Utara", "numsort" => 2130, "status" => 213, ]); 
        DB::table("city")->insert([ "id" => 214, "code" => "CITY214", "name" => "Samarinda", "displayname" => "Samarinda", "description" => "Samarinda", "numsort" => 2140, "status" => 214, ]); 
        DB::table("city")->insert([ "id" => 215, "code" => "CITY215", "name" => "Tana Tidung", "displayname" => "Tana Tidung", "description" => "Tana Tidung", "numsort" => 2150, "status" => 215, ]); 
        DB::table("city")->insert([ "id" => 216, "code" => "CITY216", "name" => "Tarakan", "displayname" => "Tarakan", "description" => "Tarakan", "numsort" => 2160, "status" => 216, ]); 
        DB::table("city")->insert([ "id" => 217, "code" => "CITY217", "name" => "Batam", "displayname" => "Batam", "description" => "Batam", "numsort" => 2170, "status" => 217, ]); 
        DB::table("city")->insert([ "id" => 218, "code" => "CITY218", "name" => "Bintan", "displayname" => "Bintan", "description" => "Bintan", "numsort" => 2180, "status" => 218, ]); 
        DB::table("city")->insert([ "id" => 219, "code" => "CITY219", "name" => "Karimun", "displayname" => "Karimun", "description" => "Karimun", "numsort" => 2190, "status" => 219, ]); 
        DB::table("city")->insert([ "id" => 220, "code" => "CITY220", "name" => "Kepulauan Anambas", "displayname" => "Kepulauan Anambas", "description" => "Kepulauan Anambas", "numsort" => 2200, "status" => 220, ]); 
        DB::table("city")->insert([ "id" => 221, "code" => "CITY221", "name" => "Lingga", "displayname" => "Lingga", "description" => "Lingga", "numsort" => 2210, "status" => 221, ]); 
        DB::table("city")->insert([ "id" => 222, "code" => "CITY222", "name" => "Natuna", "displayname" => "Natuna", "description" => "Natuna", "numsort" => 2220, "status" => 222, ]); 
        DB::table("city")->insert([ "id" => 223, "code" => "CITY223", "name" => "Tanjung Pinang", "displayname" => "Tanjung Pinang", "description" => "Tanjung Pinang", "numsort" => 2230, "status" => 223, ]); 
        DB::table("city")->insert([ "id" => 224, "code" => "CITY224", "name" => "Bandar Lampung", "displayname" => "Bandar Lampung", "description" => "Bandar Lampung", "numsort" => 2240, "status" => 224, ]); 
        DB::table("city")->insert([ "id" => 225, "code" => "CITY225", "name" => "Lampung Barat", "displayname" => "Lampung Barat", "description" => "Lampung Barat", "numsort" => 2250, "status" => 225, ]); 
        DB::table("city")->insert([ "id" => 226, "code" => "CITY226", "name" => "Lampung Selatan", "displayname" => "Lampung Selatan", "description" => "Lampung Selatan", "numsort" => 2260, "status" => 226, ]); 
        DB::table("city")->insert([ "id" => 227, "code" => "CITY227", "name" => "Lampung Tengah", "displayname" => "Lampung Tengah", "description" => "Lampung Tengah", "numsort" => 2270, "status" => 227, ]); 
        DB::table("city")->insert([ "id" => 228, "code" => "CITY228", "name" => "Lampung Timur", "displayname" => "Lampung Timur", "description" => "Lampung Timur", "numsort" => 2280, "status" => 228, ]); 
        DB::table("city")->insert([ "id" => 229, "code" => "CITY229", "name" => "Lampung Utara", "displayname" => "Lampung Utara", "description" => "Lampung Utara", "numsort" => 2290, "status" => 229, ]); 
        DB::table("city")->insert([ "id" => 230, "code" => "CITY230", "name" => "Mesuji", "displayname" => "Mesuji", "description" => "Mesuji", "numsort" => 2300, "status" => 230, ]); 
        DB::table("city")->insert([ "id" => 231, "code" => "CITY231", "name" => "Metro", "displayname" => "Metro", "description" => "Metro", "numsort" => 2310, "status" => 231, ]); 
        DB::table("city")->insert([ "id" => 232, "code" => "CITY232", "name" => "Pesawaran", "displayname" => "Pesawaran", "description" => "Pesawaran", "numsort" => 2320, "status" => 232, ]); 
        DB::table("city")->insert([ "id" => 233, "code" => "CITY233", "name" => "Pringsewu", "displayname" => "Pringsewu", "description" => "Pringsewu", "numsort" => 2330, "status" => 233, ]); 
        DB::table("city")->insert([ "id" => 234, "code" => "CITY234", "name" => "Tanggamus", "displayname" => "Tanggamus", "description" => "Tanggamus", "numsort" => 2340, "status" => 234, ]); 
        DB::table("city")->insert([ "id" => 235, "code" => "CITY235", "name" => "Tulang Bawang", "displayname" => "Tulang Bawang", "description" => "Tulang Bawang", "numsort" => 2350, "status" => 235, ]); 
        DB::table("city")->insert([ "id" => 236, "code" => "CITY236", "name" => "Tulang Bawang Barat", "displayname" => "Tulang Bawang Barat", "description" => "Tulang Bawang Barat", "numsort" => 2360, "status" => 236, ]); 
        DB::table("city")->insert([ "id" => 237, "code" => "CITY237", "name" => "Way Kanan", "displayname" => "Way Kanan", "description" => "Way Kanan", "numsort" => 2370, "status" => 237, ]); 
        DB::table("city")->insert([ "id" => 238, "code" => "CITY238", "name" => "Ambon", "displayname" => "Ambon", "description" => "Ambon", "numsort" => 2380, "status" => 238, ]); 
        DB::table("city")->insert([ "id" => 239, "code" => "CITY239", "name" => "Buru", "displayname" => "Buru", "description" => "Buru", "numsort" => 2390, "status" => 239, ]); 
        DB::table("city")->insert([ "id" => 240, "code" => "CITY240", "name" => "Buru Selatan", "displayname" => "Buru Selatan", "description" => "Buru Selatan", "numsort" => 2400, "status" => 240, ]); 
        DB::table("city")->insert([ "id" => 241, "code" => "CITY241", "name" => "Kepulauan Aru", "displayname" => "Kepulauan Aru", "description" => "Kepulauan Aru", "numsort" => 2410, "status" => 241, ]); 
        DB::table("city")->insert([ "id" => 242, "code" => "CITY242", "name" => "Maluku Barat Daya", "displayname" => "Maluku Barat Daya", "description" => "Maluku Barat Daya", "numsort" => 2420, "status" => 242, ]); 
        DB::table("city")->insert([ "id" => 243, "code" => "CITY243", "name" => "Maluku Tengah", "displayname" => "Maluku Tengah", "description" => "Maluku Tengah", "numsort" => 2430, "status" => 243, ]); 
        DB::table("city")->insert([ "id" => 244, "code" => "CITY244", "name" => "Maluku Tenggara", "displayname" => "Maluku Tenggara", "description" => "Maluku Tenggara", "numsort" => 2440, "status" => 244, ]); 
        DB::table("city")->insert([ "id" => 245, "code" => "CITY245", "name" => "Maluku Tenggara Barat", "displayname" => "Maluku Tenggara Barat", "description" => "Maluku Tenggara Barat", "numsort" => 2450, "status" => 245, ]); 
        DB::table("city")->insert([ "id" => 246, "code" => "CITY246", "name" => "Seram Bagian Barat", "displayname" => "Seram Bagian Barat", "description" => "Seram Bagian Barat", "numsort" => 2460, "status" => 246, ]); 
        DB::table("city")->insert([ "id" => 247, "code" => "CITY247", "name" => "Seram Bagian Timur", "displayname" => "Seram Bagian Timur", "description" => "Seram Bagian Timur", "numsort" => 2470, "status" => 247, ]); 
        DB::table("city")->insert([ "id" => 248, "code" => "CITY248", "name" => "Tual", "displayname" => "Tual", "description" => "Tual", "numsort" => 2480, "status" => 248, ]); 
        DB::table("city")->insert([ "id" => 249, "code" => "CITY249", "name" => "Halmahera Barat", "displayname" => "Halmahera Barat", "description" => "Halmahera Barat", "numsort" => 2490, "status" => 249, ]); 
        DB::table("city")->insert([ "id" => 250, "code" => "CITY250", "name" => "Halmahera Selatan", "displayname" => "Halmahera Selatan", "description" => "Halmahera Selatan", "numsort" => 2500, "status" => 250, ]); 
        DB::table("city")->insert([ "id" => 251, "code" => "CITY251", "name" => "Halmahera Tengah", "displayname" => "Halmahera Tengah", "description" => "Halmahera Tengah", "numsort" => 2510, "status" => 251, ]); 
        DB::table("city")->insert([ "id" => 252, "code" => "CITY252", "name" => "Halmahera Timur", "displayname" => "Halmahera Timur", "description" => "Halmahera Timur", "numsort" => 2520, "status" => 252, ]); 
        DB::table("city")->insert([ "id" => 253, "code" => "CITY253", "name" => "Halmahera Utara", "displayname" => "Halmahera Utara", "description" => "Halmahera Utara", "numsort" => 2530, "status" => 253, ]); 
        DB::table("city")->insert([ "id" => 254, "code" => "CITY254", "name" => "Kepulauan Sula", "displayname" => "Kepulauan Sula", "description" => "Kepulauan Sula", "numsort" => 2540, "status" => 254, ]); 
        DB::table("city")->insert([ "id" => 255, "code" => "CITY255", "name" => "Pulau Morotai", "displayname" => "Pulau Morotai", "description" => "Pulau Morotai", "numsort" => 2550, "status" => 255, ]); 
        DB::table("city")->insert([ "id" => 256, "code" => "CITY256", "name" => "Ternate", "displayname" => "Ternate", "description" => "Ternate", "numsort" => 2560, "status" => 256, ]); 
        DB::table("city")->insert([ "id" => 257, "code" => "CITY257", "name" => "Tidore Kepulauan", "displayname" => "Tidore Kepulauan", "description" => "Tidore Kepulauan", "numsort" => 2570, "status" => 257, ]); 
        DB::table("city")->insert([ "id" => 258, "code" => "CITY258", "name" => "Aceh Barat", "displayname" => "Aceh Barat", "description" => "Aceh Barat", "numsort" => 2580, "status" => 258, ]); 
        DB::table("city")->insert([ "id" => 259, "code" => "CITY259", "name" => "Aceh Barat Daya", "displayname" => "Aceh Barat Daya", "description" => "Aceh Barat Daya", "numsort" => 2590, "status" => 259, ]); 
        DB::table("city")->insert([ "id" => 260, "code" => "CITY260", "name" => "Aceh Besar", "displayname" => "Aceh Besar", "description" => "Aceh Besar", "numsort" => 2600, "status" => 260, ]); 
        DB::table("city")->insert([ "id" => 261, "code" => "CITY261", "name" => "Aceh Jaya", "displayname" => "Aceh Jaya", "description" => "Aceh Jaya", "numsort" => 2610, "status" => 261, ]); 
        DB::table("city")->insert([ "id" => 262, "code" => "CITY262", "name" => "Aceh Selatan", "displayname" => "Aceh Selatan", "description" => "Aceh Selatan", "numsort" => 2620, "status" => 262, ]); 
        DB::table("city")->insert([ "id" => 263, "code" => "CITY263", "name" => "Aceh Singkil", "displayname" => "Aceh Singkil", "description" => "Aceh Singkil", "numsort" => 2630, "status" => 263, ]); 
        DB::table("city")->insert([ "id" => 264, "code" => "CITY264", "name" => "Aceh Tamiang", "displayname" => "Aceh Tamiang", "description" => "Aceh Tamiang", "numsort" => 2640, "status" => 264, ]); 
        DB::table("city")->insert([ "id" => 265, "code" => "CITY265", "name" => "Aceh Tengah", "displayname" => "Aceh Tengah", "description" => "Aceh Tengah", "numsort" => 2650, "status" => 265, ]); 
        DB::table("city")->insert([ "id" => 266, "code" => "CITY266", "name" => "Aceh Tenggara", "displayname" => "Aceh Tenggara", "description" => "Aceh Tenggara", "numsort" => 2660, "status" => 266, ]); 
        DB::table("city")->insert([ "id" => 267, "code" => "CITY267", "name" => "Aceh Timur", "displayname" => "Aceh Timur", "description" => "Aceh Timur", "numsort" => 2670, "status" => 267, ]); 
        DB::table("city")->insert([ "id" => 268, "code" => "CITY268", "name" => "Aceh Utara", "displayname" => "Aceh Utara", "description" => "Aceh Utara", "numsort" => 2680, "status" => 268, ]); 
        DB::table("city")->insert([ "id" => 269, "code" => "CITY269", "name" => "Banda Aceh", "displayname" => "Banda Aceh", "description" => "Banda Aceh", "numsort" => 2690, "status" => 269, ]); 
        DB::table("city")->insert([ "id" => 270, "code" => "CITY270", "name" => "Bener Meriah", "displayname" => "Bener Meriah", "description" => "Bener Meriah", "numsort" => 2700, "status" => 270, ]); 
        DB::table("city")->insert([ "id" => 271, "code" => "CITY271", "name" => "Bireuen", "displayname" => "Bireuen", "description" => "Bireuen", "numsort" => 2710, "status" => 271, ]); 
        DB::table("city")->insert([ "id" => 272, "code" => "CITY272", "name" => "Gayo Lues", "displayname" => "Gayo Lues", "description" => "Gayo Lues", "numsort" => 2720, "status" => 272, ]); 
        DB::table("city")->insert([ "id" => 273, "code" => "CITY273", "name" => "Langsa", "displayname" => "Langsa", "description" => "Langsa", "numsort" => 2730, "status" => 273, ]); 
        DB::table("city")->insert([ "id" => 274, "code" => "CITY274", "name" => "Lhokseumawe", "displayname" => "Lhokseumawe", "description" => "Lhokseumawe", "numsort" => 2740, "status" => 274, ]); 
        DB::table("city")->insert([ "id" => 275, "code" => "CITY275", "name" => "Nagan Raya", "displayname" => "Nagan Raya", "description" => "Nagan Raya", "numsort" => 2750, "status" => 275, ]); 
        DB::table("city")->insert([ "id" => 276, "code" => "CITY276", "name" => "Pidie", "displayname" => "Pidie", "description" => "Pidie", "numsort" => 2760, "status" => 276, ]); 
        DB::table("city")->insert([ "id" => 277, "code" => "CITY277", "name" => "Pidie Jaya", "displayname" => "Pidie Jaya", "description" => "Pidie Jaya", "numsort" => 2770, "status" => 277, ]); 
        DB::table("city")->insert([ "id" => 278, "code" => "CITY278", "name" => "Sabang", "displayname" => "Sabang", "description" => "Sabang", "numsort" => 2780, "status" => 278, ]); 
        DB::table("city")->insert([ "id" => 279, "code" => "CITY279", "name" => "Simeulue", "displayname" => "Simeulue", "description" => "Simeulue", "numsort" => 2790, "status" => 279, ]); 
        DB::table("city")->insert([ "id" => 280, "code" => "CITY280", "name" => "Subulussalam", "displayname" => "Subulussalam", "description" => "Subulussalam", "numsort" => 2800, "status" => 280, ]); 
        DB::table("city")->insert([ "id" => 281, "code" => "CITY281", "name" => "Bima", "displayname" => "Bima", "description" => "Bima", "numsort" => 2810, "status" => 281, ]); 
        DB::table("city")->insert([ "id" => 282, "code" => "CITY282", "name" => "Bima", "displayname" => "Bima", "description" => "Bima", "numsort" => 2820, "status" => 282, ]); 
        DB::table("city")->insert([ "id" => 283, "code" => "CITY283", "name" => "Dompu", "displayname" => "Dompu", "description" => "Dompu", "numsort" => 2830, "status" => 283, ]); 
        DB::table("city")->insert([ "id" => 284, "code" => "CITY284", "name" => "Lombok Barat", "displayname" => "Lombok Barat", "description" => "Lombok Barat", "numsort" => 2840, "status" => 284, ]); 
        DB::table("city")->insert([ "id" => 285, "code" => "CITY285", "name" => "Lombok Tengah", "displayname" => "Lombok Tengah", "description" => "Lombok Tengah", "numsort" => 2850, "status" => 285, ]); 
        DB::table("city")->insert([ "id" => 286, "code" => "CITY286", "name" => "Lombok Timur", "displayname" => "Lombok Timur", "description" => "Lombok Timur", "numsort" => 2860, "status" => 286, ]); 
        DB::table("city")->insert([ "id" => 287, "code" => "CITY287", "name" => "Lombok Utara", "displayname" => "Lombok Utara", "description" => "Lombok Utara", "numsort" => 2870, "status" => 287, ]); 
        DB::table("city")->insert([ "id" => 288, "code" => "CITY288", "name" => "Mataram", "displayname" => "Mataram", "description" => "Mataram", "numsort" => 2880, "status" => 288, ]); 
        DB::table("city")->insert([ "id" => 289, "code" => "CITY289", "name" => "Sumbawa", "displayname" => "Sumbawa", "description" => "Sumbawa", "numsort" => 2890, "status" => 289, ]); 
        DB::table("city")->insert([ "id" => 290, "code" => "CITY290", "name" => "Sumbawa Barat", "displayname" => "Sumbawa Barat", "description" => "Sumbawa Barat", "numsort" => 2900, "status" => 290, ]); 
        DB::table("city")->insert([ "id" => 291, "code" => "CITY291", "name" => "Alor", "displayname" => "Alor", "description" => "Alor", "numsort" => 2910, "status" => 291, ]); 
        DB::table("city")->insert([ "id" => 292, "code" => "CITY292", "name" => "Belu", "displayname" => "Belu", "description" => "Belu", "numsort" => 2920, "status" => 292, ]); 
        DB::table("city")->insert([ "id" => 293, "code" => "CITY293", "name" => "Ende", "displayname" => "Ende", "description" => "Ende", "numsort" => 2930, "status" => 293, ]); 
        DB::table("city")->insert([ "id" => 294, "code" => "CITY294", "name" => "Flores Timur", "displayname" => "Flores Timur", "description" => "Flores Timur", "numsort" => 2940, "status" => 294, ]); 
        DB::table("city")->insert([ "id" => 295, "code" => "CITY295", "name" => "Kupang", "displayname" => "Kupang", "description" => "Kupang", "numsort" => 2950, "status" => 295, ]); 
        DB::table("city")->insert([ "id" => 296, "code" => "CITY296", "name" => "Kupang", "displayname" => "Kupang", "description" => "Kupang", "numsort" => 2960, "status" => 296, ]); 
        DB::table("city")->insert([ "id" => 297, "code" => "CITY297", "name" => "Lembata", "displayname" => "Lembata", "description" => "Lembata", "numsort" => 2970, "status" => 297, ]); 
        DB::table("city")->insert([ "id" => 298, "code" => "CITY298", "name" => "Manggarai", "displayname" => "Manggarai", "description" => "Manggarai", "numsort" => 2980, "status" => 298, ]); 
        DB::table("city")->insert([ "id" => 299, "code" => "CITY299", "name" => "Manggarai Barat", "displayname" => "Manggarai Barat", "description" => "Manggarai Barat", "numsort" => 2990, "status" => 299, ]); 
        DB::table("city")->insert([ "id" => 300, "code" => "CITY300", "name" => "Manggarai Timur", "displayname" => "Manggarai Timur", "description" => "Manggarai Timur", "numsort" => 3000, "status" => 300, ]); 
        DB::table("city")->insert([ "id" => 301, "code" => "CITY301", "name" => "Nagekeo", "displayname" => "Nagekeo", "description" => "Nagekeo", "numsort" => 3010, "status" => 301, ]); 
        DB::table("city")->insert([ "id" => 302, "code" => "CITY302", "name" => "Ngada", "displayname" => "Ngada", "description" => "Ngada", "numsort" => 3020, "status" => 302, ]); 
        DB::table("city")->insert([ "id" => 303, "code" => "CITY303", "name" => "Rote Ndao", "displayname" => "Rote Ndao", "description" => "Rote Ndao", "numsort" => 3030, "status" => 303, ]); 
        DB::table("city")->insert([ "id" => 304, "code" => "CITY304", "name" => "Sabu Raijua", "displayname" => "Sabu Raijua", "description" => "Sabu Raijua", "numsort" => 3040, "status" => 304, ]); 
        DB::table("city")->insert([ "id" => 305, "code" => "CITY305", "name" => "Sikka", "displayname" => "Sikka", "description" => "Sikka", "numsort" => 3050, "status" => 305, ]); 
        DB::table("city")->insert([ "id" => 306, "code" => "CITY306", "name" => "Sumba Barat", "displayname" => "Sumba Barat", "description" => "Sumba Barat", "numsort" => 3060, "status" => 306, ]); 
        DB::table("city")->insert([ "id" => 307, "code" => "CITY307", "name" => "Sumba Barat Daya", "displayname" => "Sumba Barat Daya", "description" => "Sumba Barat Daya", "numsort" => 3070, "status" => 307, ]); 
        DB::table("city")->insert([ "id" => 308, "code" => "CITY308", "name" => "Sumba Tengah", "displayname" => "Sumba Tengah", "description" => "Sumba Tengah", "numsort" => 3080, "status" => 308, ]); 
        DB::table("city")->insert([ "id" => 309, "code" => "CITY309", "name" => "Sumba Timur", "displayname" => "Sumba Timur", "description" => "Sumba Timur", "numsort" => 3090, "status" => 309, ]); 
        DB::table("city")->insert([ "id" => 310, "code" => "CITY310", "name" => "Timor Tengah Selatan", "displayname" => "Timor Tengah Selatan", "description" => "Timor Tengah Selatan", "numsort" => 3100, "status" => 310, ]); 
        DB::table("city")->insert([ "id" => 311, "code" => "CITY311", "name" => "Timor Tengah Utara", "displayname" => "Timor Tengah Utara", "description" => "Timor Tengah Utara", "numsort" => 3110, "status" => 311, ]); 
        DB::table("city")->insert([ "id" => 312, "code" => "CITY312", "name" => "Asmat", "displayname" => "Asmat", "description" => "Asmat", "numsort" => 3120, "status" => 312, ]); 
        DB::table("city")->insert([ "id" => 313, "code" => "CITY313", "name" => "Biak Numfor", "displayname" => "Biak Numfor", "description" => "Biak Numfor", "numsort" => 3130, "status" => 313, ]); 
        DB::table("city")->insert([ "id" => 314, "code" => "CITY314", "name" => "Boven Digoel", "displayname" => "Boven Digoel", "description" => "Boven Digoel", "numsort" => 3140, "status" => 314, ]); 
        DB::table("city")->insert([ "id" => 315, "code" => "CITY315", "name" => "Deiyai (Deliyai)", "displayname" => "Deiyai (Deliyai)", "description" => "Deiyai (Deliyai)", "numsort" => 3150, "status" => 315, ]); 
        DB::table("city")->insert([ "id" => 316, "code" => "CITY316", "name" => "Dogiyai", "displayname" => "Dogiyai", "description" => "Dogiyai", "numsort" => 3160, "status" => 316, ]); 
        DB::table("city")->insert([ "id" => 317, "code" => "CITY317", "name" => "Intan Jaya", "displayname" => "Intan Jaya", "description" => "Intan Jaya", "numsort" => 3170, "status" => 317, ]); 
        DB::table("city")->insert([ "id" => 318, "code" => "CITY318", "name" => "Jayapura", "displayname" => "Jayapura", "description" => "Jayapura", "numsort" => 3180, "status" => 318, ]); 
        DB::table("city")->insert([ "id" => 319, "code" => "CITY319", "name" => "Jayapura", "displayname" => "Jayapura", "description" => "Jayapura", "numsort" => 3190, "status" => 319, ]); 
        DB::table("city")->insert([ "id" => 320, "code" => "CITY320", "name" => "Jayawijaya", "displayname" => "Jayawijaya", "description" => "Jayawijaya", "numsort" => 3200, "status" => 320, ]); 
        DB::table("city")->insert([ "id" => 321, "code" => "CITY321", "name" => "Keerom", "displayname" => "Keerom", "description" => "Keerom", "numsort" => 3210, "status" => 321, ]); 
        DB::table("city")->insert([ "id" => 322, "code" => "CITY322", "name" => "Kepulauan Yapen (Yapen Waropen)", "displayname" => "Kepulauan Yapen (Yapen Waropen)", "description" => "Kepulauan Yapen (Yapen Waropen)", "numsort" => 3220, "status" => 322, ]); 
        DB::table("city")->insert([ "id" => 323, "code" => "CITY323", "name" => "Lanny Jaya", "displayname" => "Lanny Jaya", "description" => "Lanny Jaya", "numsort" => 3230, "status" => 323, ]); 
        DB::table("city")->insert([ "id" => 324, "code" => "CITY324", "name" => "Mamberamo Raya", "displayname" => "Mamberamo Raya", "description" => "Mamberamo Raya", "numsort" => 3240, "status" => 324, ]); 
        DB::table("city")->insert([ "id" => 325, "code" => "CITY325", "name" => "Mamberamo Tengah", "displayname" => "Mamberamo Tengah", "description" => "Mamberamo Tengah", "numsort" => 3250, "status" => 325, ]); 
        DB::table("city")->insert([ "id" => 326, "code" => "CITY326", "name" => "Mappi", "displayname" => "Mappi", "description" => "Mappi", "numsort" => 3260, "status" => 326, ]); 
        DB::table("city")->insert([ "id" => 327, "code" => "CITY327", "name" => "Merauke", "displayname" => "Merauke", "description" => "Merauke", "numsort" => 3270, "status" => 327, ]); 
        DB::table("city")->insert([ "id" => 328, "code" => "CITY328", "name" => "Mimika", "displayname" => "Mimika", "description" => "Mimika", "numsort" => 3280, "status" => 328, ]); 
        DB::table("city")->insert([ "id" => 329, "code" => "CITY329", "name" => "Nabire", "displayname" => "Nabire", "description" => "Nabire", "numsort" => 3290, "status" => 329, ]); 
        DB::table("city")->insert([ "id" => 330, "code" => "CITY330", "name" => "Nduga", "displayname" => "Nduga", "description" => "Nduga", "numsort" => 3300, "status" => 330, ]); 
        DB::table("city")->insert([ "id" => 331, "code" => "CITY331", "name" => "Paniai", "displayname" => "Paniai", "description" => "Paniai", "numsort" => 3310, "status" => 331, ]); 
        DB::table("city")->insert([ "id" => 332, "code" => "CITY332", "name" => "Pegunungan Bintang", "displayname" => "Pegunungan Bintang", "description" => "Pegunungan Bintang", "numsort" => 3320, "status" => 332, ]); 
        DB::table("city")->insert([ "id" => 333, "code" => "CITY333", "name" => "Puncak", "displayname" => "Puncak", "description" => "Puncak", "numsort" => 3330, "status" => 333, ]); 
        DB::table("city")->insert([ "id" => 334, "code" => "CITY334", "name" => "Puncak Jaya", "displayname" => "Puncak Jaya", "description" => "Puncak Jaya", "numsort" => 3340, "status" => 334, ]); 
        DB::table("city")->insert([ "id" => 335, "code" => "CITY335", "name" => "Sarmi", "displayname" => "Sarmi", "description" => "Sarmi", "numsort" => 3350, "status" => 335, ]); 
        DB::table("city")->insert([ "id" => 336, "code" => "CITY336", "name" => "Supiori", "displayname" => "Supiori", "description" => "Supiori", "numsort" => 3360, "status" => 336, ]); 
        DB::table("city")->insert([ "id" => 337, "code" => "CITY337", "name" => "Tolikara", "displayname" => "Tolikara", "description" => "Tolikara", "numsort" => 3370, "status" => 337, ]); 
        DB::table("city")->insert([ "id" => 338, "code" => "CITY338", "name" => "Waropen", "displayname" => "Waropen", "description" => "Waropen", "numsort" => 3380, "status" => 338, ]); 
        DB::table("city")->insert([ "id" => 339, "code" => "CITY339", "name" => "Yahukimo", "displayname" => "Yahukimo", "description" => "Yahukimo", "numsort" => 3390, "status" => 339, ]); 
        DB::table("city")->insert([ "id" => 340, "code" => "CITY340", "name" => "Yalimo", "displayname" => "Yalimo", "description" => "Yalimo", "numsort" => 3400, "status" => 340, ]); 
        DB::table("city")->insert([ "id" => 341, "code" => "CITY341", "name" => "Fakfak", "displayname" => "Fakfak", "description" => "Fakfak", "numsort" => 3410, "status" => 341, ]); 
        DB::table("city")->insert([ "id" => 342, "code" => "CITY342", "name" => "Kaimana", "displayname" => "Kaimana", "description" => "Kaimana", "numsort" => 3420, "status" => 342, ]); 
        DB::table("city")->insert([ "id" => 343, "code" => "CITY343", "name" => "Manokwari", "displayname" => "Manokwari", "description" => "Manokwari", "numsort" => 3430, "status" => 343, ]); 
        DB::table("city")->insert([ "id" => 344, "code" => "CITY344", "name" => "Maybrat", "displayname" => "Maybrat", "description" => "Maybrat", "numsort" => 3440, "status" => 344, ]); 
        DB::table("city")->insert([ "id" => 345, "code" => "CITY345", "name" => "Raja Ampat", "displayname" => "Raja Ampat", "description" => "Raja Ampat", "numsort" => 3450, "status" => 345, ]); 
        DB::table("city")->insert([ "id" => 346, "code" => "CITY346", "name" => "Sorong", "displayname" => "Sorong", "description" => "Sorong", "numsort" => 3460, "status" => 346, ]); 
        DB::table("city")->insert([ "id" => 347, "code" => "CITY347", "name" => "Sorong", "displayname" => "Sorong", "description" => "Sorong", "numsort" => 3470, "status" => 347, ]); 
        DB::table("city")->insert([ "id" => 348, "code" => "CITY348", "name" => "Sorong Selatan", "displayname" => "Sorong Selatan", "description" => "Sorong Selatan", "numsort" => 3480, "status" => 348, ]); 
        DB::table("city")->insert([ "id" => 349, "code" => "CITY349", "name" => "Tambrauw", "displayname" => "Tambrauw", "description" => "Tambrauw", "numsort" => 3490, "status" => 349, ]); 
        DB::table("city")->insert([ "id" => 350, "code" => "CITY350", "name" => "Teluk Bintuni", "displayname" => "Teluk Bintuni", "description" => "Teluk Bintuni", "numsort" => 3500, "status" => 350, ]); 
        DB::table("city")->insert([ "id" => 351, "code" => "CITY351", "name" => "Teluk Wondama", "displayname" => "Teluk Wondama", "description" => "Teluk Wondama", "numsort" => 3510, "status" => 351, ]); 
        DB::table("city")->insert([ "id" => 352, "code" => "CITY352", "name" => "Bengkalis", "displayname" => "Bengkalis", "description" => "Bengkalis", "numsort" => 3520, "status" => 352, ]); 
        DB::table("city")->insert([ "id" => 353, "code" => "CITY353", "name" => "Dumai", "displayname" => "Dumai", "description" => "Dumai", "numsort" => 3530, "status" => 353, ]); 
        DB::table("city")->insert([ "id" => 354, "code" => "CITY354", "name" => "Indragiri Hilir", "displayname" => "Indragiri Hilir", "description" => "Indragiri Hilir", "numsort" => 3540, "status" => 354, ]); 
        DB::table("city")->insert([ "id" => 355, "code" => "CITY355", "name" => "Indragiri Hulu", "displayname" => "Indragiri Hulu", "description" => "Indragiri Hulu", "numsort" => 3550, "status" => 355, ]); 
        DB::table("city")->insert([ "id" => 356, "code" => "CITY356", "name" => "Kampar", "displayname" => "Kampar", "description" => "Kampar", "numsort" => 3560, "status" => 356, ]); 
        DB::table("city")->insert([ "id" => 357, "code" => "CITY357", "name" => "Kepulauan Meranti", "displayname" => "Kepulauan Meranti", "description" => "Kepulauan Meranti", "numsort" => 3570, "status" => 357, ]); 
        DB::table("city")->insert([ "id" => 358, "code" => "CITY358", "name" => "Kuantan Singingi", "displayname" => "Kuantan Singingi", "description" => "Kuantan Singingi", "numsort" => 3580, "status" => 358, ]); 
        DB::table("city")->insert([ "id" => 359, "code" => "CITY359", "name" => "Pekanbaru", "displayname" => "Pekanbaru", "description" => "Pekanbaru", "numsort" => 3590, "status" => 359, ]); 
        DB::table("city")->insert([ "id" => 360, "code" => "CITY360", "name" => "Pelalawan", "displayname" => "Pelalawan", "description" => "Pelalawan", "numsort" => 3600, "status" => 360, ]); 
        DB::table("city")->insert([ "id" => 361, "code" => "CITY361", "name" => "Rokan Hilir", "displayname" => "Rokan Hilir", "description" => "Rokan Hilir", "numsort" => 3610, "status" => 361, ]); 
        DB::table("city")->insert([ "id" => 362, "code" => "CITY362", "name" => "Rokan Hulu", "displayname" => "Rokan Hulu", "description" => "Rokan Hulu", "numsort" => 3620, "status" => 362, ]); 
        DB::table("city")->insert([ "id" => 363, "code" => "CITY363", "name" => "Siak", "displayname" => "Siak", "description" => "Siak", "numsort" => 3630, "status" => 363, ]); 
        DB::table("city")->insert([ "id" => 364, "code" => "CITY364", "name" => "Majene", "displayname" => "Majene", "description" => "Majene", "numsort" => 3640, "status" => 364, ]); 
        DB::table("city")->insert([ "id" => 365, "code" => "CITY365", "name" => "Mamasa", "displayname" => "Mamasa", "description" => "Mamasa", "numsort" => 3650, "status" => 365, ]); 
        DB::table("city")->insert([ "id" => 366, "code" => "CITY366", "name" => "Mamuju", "displayname" => "Mamuju", "description" => "Mamuju", "numsort" => 3660, "status" => 366, ]); 
        DB::table("city")->insert([ "id" => 367, "code" => "CITY367", "name" => "Mamuju Utara", "displayname" => "Mamuju Utara", "description" => "Mamuju Utara", "numsort" => 3670, "status" => 367, ]); 
        DB::table("city")->insert([ "id" => 368, "code" => "CITY368", "name" => "Polewali Mandar", "displayname" => "Polewali Mandar", "description" => "Polewali Mandar", "numsort" => 3680, "status" => 368, ]); 
        DB::table("city")->insert([ "id" => 369, "code" => "CITY369", "name" => "Bantaeng", "displayname" => "Bantaeng", "description" => "Bantaeng", "numsort" => 3690, "status" => 369, ]); 
        DB::table("city")->insert([ "id" => 370, "code" => "CITY370", "name" => "Barru", "displayname" => "Barru", "description" => "Barru", "numsort" => 3700, "status" => 370, ]); 
        DB::table("city")->insert([ "id" => 371, "code" => "CITY371", "name" => "Bone", "displayname" => "Bone", "description" => "Bone", "numsort" => 3710, "status" => 371, ]); 
        DB::table("city")->insert([ "id" => 372, "code" => "CITY372", "name" => "Bulukumba", "displayname" => "Bulukumba", "description" => "Bulukumba", "numsort" => 3720, "status" => 372, ]); 
        DB::table("city")->insert([ "id" => 373, "code" => "CITY373", "name" => "Enrekang", "displayname" => "Enrekang", "description" => "Enrekang", "numsort" => 3730, "status" => 373, ]); 
        DB::table("city")->insert([ "id" => 374, "code" => "CITY374", "name" => "Gowa", "displayname" => "Gowa", "description" => "Gowa", "numsort" => 3740, "status" => 374, ]); 
        DB::table("city")->insert([ "id" => 375, "code" => "CITY375", "name" => "Jeneponto", "displayname" => "Jeneponto", "description" => "Jeneponto", "numsort" => 3750, "status" => 375, ]); 
        DB::table("city")->insert([ "id" => 376, "code" => "CITY376", "name" => "Luwu", "displayname" => "Luwu", "description" => "Luwu", "numsort" => 3760, "status" => 376, ]); 
        DB::table("city")->insert([ "id" => 377, "code" => "CITY377", "name" => "Luwu Timur", "displayname" => "Luwu Timur", "description" => "Luwu Timur", "numsort" => 3770, "status" => 377, ]); 
        DB::table("city")->insert([ "id" => 378, "code" => "CITY378", "name" => "Luwu Utara", "displayname" => "Luwu Utara", "description" => "Luwu Utara", "numsort" => 3780, "status" => 378, ]); 
        DB::table("city")->insert([ "id" => 379, "code" => "CITY379", "name" => "Makassar", "displayname" => "Makassar", "description" => "Makassar", "numsort" => 3790, "status" => 379, ]); 
        DB::table("city")->insert([ "id" => 380, "code" => "CITY380", "name" => "Maros", "displayname" => "Maros", "description" => "Maros", "numsort" => 3800, "status" => 380, ]); 
        DB::table("city")->insert([ "id" => 381, "code" => "CITY381", "name" => "Palopo", "displayname" => "Palopo", "description" => "Palopo", "numsort" => 3810, "status" => 381, ]); 
        DB::table("city")->insert([ "id" => 382, "code" => "CITY382", "name" => "Pangkajene Kepulauan", "displayname" => "Pangkajene Kepulauan", "description" => "Pangkajene Kepulauan", "numsort" => 3820, "status" => 382, ]); 
        DB::table("city")->insert([ "id" => 383, "code" => "CITY383", "name" => "Parepare", "displayname" => "Parepare", "description" => "Parepare", "numsort" => 3830, "status" => 383, ]); 
        DB::table("city")->insert([ "id" => 384, "code" => "CITY384", "name" => "Pinrang", "displayname" => "Pinrang", "description" => "Pinrang", "numsort" => 3840, "status" => 384, ]); 
        DB::table("city")->insert([ "id" => 385, "code" => "CITY385", "name" => "Selayar (Kepulauan Selayar)", "displayname" => "Selayar (Kepulauan Selayar)", "description" => "Selayar (Kepulauan Selayar)", "numsort" => 3850, "status" => 385, ]); 
        DB::table("city")->insert([ "id" => 386, "code" => "CITY386", "name" => "Sidenreng Rappang/Rapang", "displayname" => "Sidenreng Rappang/Rapang", "description" => "Sidenreng Rappang/Rapang", "numsort" => 3860, "status" => 386, ]); 
        DB::table("city")->insert([ "id" => 387, "code" => "CITY387", "name" => "Sinjai", "displayname" => "Sinjai", "description" => "Sinjai", "numsort" => 3870, "status" => 387, ]); 
        DB::table("city")->insert([ "id" => 388, "code" => "CITY388", "name" => "Soppeng", "displayname" => "Soppeng", "description" => "Soppeng", "numsort" => 3880, "status" => 388, ]); 
        DB::table("city")->insert([ "id" => 389, "code" => "CITY389", "name" => "Takalar", "displayname" => "Takalar", "description" => "Takalar", "numsort" => 3890, "status" => 389, ]); 
        DB::table("city")->insert([ "id" => 390, "code" => "CITY390", "name" => "Tana Toraja", "displayname" => "Tana Toraja", "description" => "Tana Toraja", "numsort" => 3900, "status" => 390, ]); 
        DB::table("city")->insert([ "id" => 391, "code" => "CITY391", "name" => "Toraja Utara", "displayname" => "Toraja Utara", "description" => "Toraja Utara", "numsort" => 3910, "status" => 391, ]); 
        DB::table("city")->insert([ "id" => 392, "code" => "CITY392", "name" => "Wajo", "displayname" => "Wajo", "description" => "Wajo", "numsort" => 3920, "status" => 392, ]); 
        DB::table("city")->insert([ "id" => 393, "code" => "CITY393", "name" => "Banggai", "displayname" => "Banggai", "description" => "Banggai", "numsort" => 3930, "status" => 393, ]); 
        DB::table("city")->insert([ "id" => 394, "code" => "CITY394", "name" => "Banggai Kepulauan", "displayname" => "Banggai Kepulauan", "description" => "Banggai Kepulauan", "numsort" => 3940, "status" => 394, ]); 
        DB::table("city")->insert([ "id" => 395, "code" => "CITY395", "name" => "Buol", "displayname" => "Buol", "description" => "Buol", "numsort" => 3950, "status" => 395, ]); 
        DB::table("city")->insert([ "id" => 396, "code" => "CITY396", "name" => "Donggala", "displayname" => "Donggala", "description" => "Donggala", "numsort" => 3960, "status" => 396, ]); 
        DB::table("city")->insert([ "id" => 397, "code" => "CITY397", "name" => "Morowali", "displayname" => "Morowali", "description" => "Morowali", "numsort" => 3970, "status" => 397, ]); 
        DB::table("city")->insert([ "id" => 398, "code" => "CITY398", "name" => "Palu", "displayname" => "Palu", "description" => "Palu", "numsort" => 3980, "status" => 398, ]); 
        DB::table("city")->insert([ "id" => 399, "code" => "CITY399", "name" => "Parigi Moutong", "displayname" => "Parigi Moutong", "description" => "Parigi Moutong", "numsort" => 3990, "status" => 399, ]); 
        DB::table("city")->insert([ "id" => 400, "code" => "CITY400", "name" => "Poso", "displayname" => "Poso", "description" => "Poso", "numsort" => 4000, "status" => 400, ]); 
        DB::table("city")->insert([ "id" => 401, "code" => "CITY401", "name" => "Sigi", "displayname" => "Sigi", "description" => "Sigi", "numsort" => 4010, "status" => 401, ]); 
        DB::table("city")->insert([ "id" => 402, "code" => "CITY402", "name" => "Tojo Una-Una", "displayname" => "Tojo Una-Una", "description" => "Tojo Una-Una", "numsort" => 4020, "status" => 402, ]); 
        DB::table("city")->insert([ "id" => 403, "code" => "CITY403", "name" => "Toli-Toli", "displayname" => "Toli-Toli", "description" => "Toli-Toli", "numsort" => 4030, "status" => 403, ]); 
        DB::table("city")->insert([ "id" => 404, "code" => "CITY404", "name" => "Bau-Bau", "displayname" => "Bau-Bau", "description" => "Bau-Bau", "numsort" => 4040, "status" => 404, ]); 
        DB::table("city")->insert([ "id" => 405, "code" => "CITY405", "name" => "Bombana", "displayname" => "Bombana", "description" => "Bombana", "numsort" => 4050, "status" => 405, ]); 
        DB::table("city")->insert([ "id" => 406, "code" => "CITY406", "name" => "Buton", "displayname" => "Buton", "description" => "Buton", "numsort" => 4060, "status" => 406, ]); 
        DB::table("city")->insert([ "id" => 407, "code" => "CITY407", "name" => "Buton Utara", "displayname" => "Buton Utara", "description" => "Buton Utara", "numsort" => 4070, "status" => 407, ]); 
        DB::table("city")->insert([ "id" => 408, "code" => "CITY408", "name" => "Kendari", "displayname" => "Kendari", "description" => "Kendari", "numsort" => 4080, "status" => 408, ]); 
        DB::table("city")->insert([ "id" => 409, "code" => "CITY409", "name" => "Kolaka", "displayname" => "Kolaka", "description" => "Kolaka", "numsort" => 4090, "status" => 409, ]); 
        DB::table("city")->insert([ "id" => 410, "code" => "CITY410", "name" => "Kolaka Utara", "displayname" => "Kolaka Utara", "description" => "Kolaka Utara", "numsort" => 4100, "status" => 410, ]); 
        DB::table("city")->insert([ "id" => 411, "code" => "CITY411", "name" => "Konawe", "displayname" => "Konawe", "description" => "Konawe", "numsort" => 4110, "status" => 411, ]); 
        DB::table("city")->insert([ "id" => 412, "code" => "CITY412", "name" => "Konawe Selatan", "displayname" => "Konawe Selatan", "description" => "Konawe Selatan", "numsort" => 4120, "status" => 412, ]); 
        DB::table("city")->insert([ "id" => 413, "code" => "CITY413", "name" => "Konawe Utara", "displayname" => "Konawe Utara", "description" => "Konawe Utara", "numsort" => 4130, "status" => 413, ]); 
        DB::table("city")->insert([ "id" => 414, "code" => "CITY414", "name" => "Muna", "displayname" => "Muna", "description" => "Muna", "numsort" => 4140, "status" => 414, ]); 
        DB::table("city")->insert([ "id" => 415, "code" => "CITY415", "name" => "Wakatobi", "displayname" => "Wakatobi", "description" => "Wakatobi", "numsort" => 4150, "status" => 415, ]); 
        DB::table("city")->insert([ "id" => 416, "code" => "CITY416", "name" => "Bitung", "displayname" => "Bitung", "description" => "Bitung", "numsort" => 4160, "status" => 416, ]); 
        DB::table("city")->insert([ "id" => 417, "code" => "CITY417", "name" => "Bolaang Mongondow (Bolmong)", "displayname" => "Bolaang Mongondow (Bolmong)", "description" => "Bolaang Mongondow (Bolmong)", "numsort" => 4170, "status" => 417, ]); 
        DB::table("city")->insert([ "id" => 418, "code" => "CITY418", "name" => "Bolaang Mongondow Selatan", "displayname" => "Bolaang Mongondow Selatan", "description" => "Bolaang Mongondow Selatan", "numsort" => 4180, "status" => 418, ]); 
        DB::table("city")->insert([ "id" => 419, "code" => "CITY419", "name" => "Bolaang Mongondow Timur", "displayname" => "Bolaang Mongondow Timur", "description" => "Bolaang Mongondow Timur", "numsort" => 4190, "status" => 419, ]); 
        DB::table("city")->insert([ "id" => 420, "code" => "CITY420", "name" => "Bolaang Mongondow Utara", "displayname" => "Bolaang Mongondow Utara", "description" => "Bolaang Mongondow Utara", "numsort" => 4200, "status" => 420, ]); 
        DB::table("city")->insert([ "id" => 421, "code" => "CITY421", "name" => "Kepulauan Sangihe", "displayname" => "Kepulauan Sangihe", "description" => "Kepulauan Sangihe", "numsort" => 4210, "status" => 421, ]); 
        DB::table("city")->insert([ "id" => 422, "code" => "CITY422", "name" => "Kepulauan Siau Tagulandang Biaro (Sitaro)", "displayname" => "Kepulauan Siau Tagulandang Biaro (Sitaro)", "description" => "Kepulauan Siau Tagulandang Biaro (Sitaro)", "numsort" => 4220, "status" => 422, ]); 
        DB::table("city")->insert([ "id" => 423, "code" => "CITY423", "name" => "Kepulauan Talaud", "displayname" => "Kepulauan Talaud", "description" => "Kepulauan Talaud", "numsort" => 4230, "status" => 423, ]); 
        DB::table("city")->insert([ "id" => 424, "code" => "CITY424", "name" => "Kotamobagu", "displayname" => "Kotamobagu", "description" => "Kotamobagu", "numsort" => 4240, "status" => 424, ]); 
        DB::table("city")->insert([ "id" => 425, "code" => "CITY425", "name" => "Manado", "displayname" => "Manado", "description" => "Manado", "numsort" => 4250, "status" => 425, ]); 
        DB::table("city")->insert([ "id" => 426, "code" => "CITY426", "name" => "Minahasa", "displayname" => "Minahasa", "description" => "Minahasa", "numsort" => 4260, "status" => 426, ]); 
        DB::table("city")->insert([ "id" => 427, "code" => "CITY427", "name" => "Minahasa Selatan", "displayname" => "Minahasa Selatan", "description" => "Minahasa Selatan", "numsort" => 4270, "status" => 427, ]); 
        DB::table("city")->insert([ "id" => 428, "code" => "CITY428", "name" => "Minahasa Tenggara", "displayname" => "Minahasa Tenggara", "description" => "Minahasa Tenggara", "numsort" => 4280, "status" => 428, ]); 
        DB::table("city")->insert([ "id" => 429, "code" => "CITY429", "name" => "Minahasa Utara", "displayname" => "Minahasa Utara", "description" => "Minahasa Utara", "numsort" => 4290, "status" => 429, ]); 
        DB::table("city")->insert([ "id" => 430, "code" => "CITY430", "name" => "Tomohon", "displayname" => "Tomohon", "description" => "Tomohon", "numsort" => 4300, "status" => 430, ]); 
        DB::table("city")->insert([ "id" => 431, "code" => "CITY431", "name" => "Agam", "displayname" => "Agam", "description" => "Agam", "numsort" => 4310, "status" => 431, ]); 
        DB::table("city")->insert([ "id" => 432, "code" => "CITY432", "name" => "Bukittinggi", "displayname" => "Bukittinggi", "description" => "Bukittinggi", "numsort" => 4320, "status" => 432, ]); 
        DB::table("city")->insert([ "id" => 433, "code" => "CITY433", "name" => "Dharmasraya", "displayname" => "Dharmasraya", "description" => "Dharmasraya", "numsort" => 4330, "status" => 433, ]); 
        DB::table("city")->insert([ "id" => 434, "code" => "CITY434", "name" => "Kepulauan Mentawai", "displayname" => "Kepulauan Mentawai", "description" => "Kepulauan Mentawai", "numsort" => 4340, "status" => 434, ]); 
        DB::table("city")->insert([ "id" => 435, "code" => "CITY435", "name" => "Lima Puluh Koto/Kota", "displayname" => "Lima Puluh Koto/Kota", "description" => "Lima Puluh Koto/Kota", "numsort" => 4350, "status" => 435, ]); 
        DB::table("city")->insert([ "id" => 436, "code" => "CITY436", "name" => "Padang", "displayname" => "Padang", "description" => "Padang", "numsort" => 4360, "status" => 436, ]); 
        DB::table("city")->insert([ "id" => 437, "code" => "CITY437", "name" => "Padang Panjang", "displayname" => "Padang Panjang", "description" => "Padang Panjang", "numsort" => 4370, "status" => 437, ]); 
        DB::table("city")->insert([ "id" => 438, "code" => "CITY438", "name" => "Padang Pariaman", "displayname" => "Padang Pariaman", "description" => "Padang Pariaman", "numsort" => 4380, "status" => 438, ]); 
        DB::table("city")->insert([ "id" => 439, "code" => "CITY439", "name" => "Pariaman", "displayname" => "Pariaman", "description" => "Pariaman", "numsort" => 4390, "status" => 439, ]); 
        DB::table("city")->insert([ "id" => 440, "code" => "CITY440", "name" => "Pasaman", "displayname" => "Pasaman", "description" => "Pasaman", "numsort" => 4400, "status" => 440, ]); 
        DB::table("city")->insert([ "id" => 441, "code" => "CITY441", "name" => "Pasaman Barat", "displayname" => "Pasaman Barat", "description" => "Pasaman Barat", "numsort" => 4410, "status" => 441, ]); 
        DB::table("city")->insert([ "id" => 442, "code" => "CITY442", "name" => "Payakumbuh", "displayname" => "Payakumbuh", "description" => "Payakumbuh", "numsort" => 4420, "status" => 442, ]); 
        DB::table("city")->insert([ "id" => 443, "code" => "CITY443", "name" => "Pesisir Selatan", "displayname" => "Pesisir Selatan", "description" => "Pesisir Selatan", "numsort" => 4430, "status" => 443, ]); 
        DB::table("city")->insert([ "id" => 444, "code" => "CITY444", "name" => "Sawah Lunto", "displayname" => "Sawah Lunto", "description" => "Sawah Lunto", "numsort" => 4440, "status" => 444, ]); 
        DB::table("city")->insert([ "id" => 445, "code" => "CITY445", "name" => "Sijunjung (Sawah Lunto Sijunjung)", "displayname" => "Sijunjung (Sawah Lunto Sijunjung)", "description" => "Sijunjung (Sawah Lunto Sijunjung)", "numsort" => 4450, "status" => 445, ]); 
        DB::table("city")->insert([ "id" => 446, "code" => "CITY446", "name" => "Solok", "displayname" => "Solok", "description" => "Solok", "numsort" => 4460, "status" => 446, ]); 
        DB::table("city")->insert([ "id" => 447, "code" => "CITY447", "name" => "Solok", "displayname" => "Solok", "description" => "Solok", "numsort" => 4470, "status" => 447, ]); 
        DB::table("city")->insert([ "id" => 448, "code" => "CITY448", "name" => "Solok Selatan", "displayname" => "Solok Selatan", "description" => "Solok Selatan", "numsort" => 4480, "status" => 448, ]); 
        DB::table("city")->insert([ "id" => 449, "code" => "CITY449", "name" => "Tanah Datar", "displayname" => "Tanah Datar", "description" => "Tanah Datar", "numsort" => 4490, "status" => 449, ]); 
        DB::table("city")->insert([ "id" => 450, "code" => "CITY450", "name" => "Banyuasin", "displayname" => "Banyuasin", "description" => "Banyuasin", "numsort" => 4500, "status" => 450, ]); 
        DB::table("city")->insert([ "id" => 451, "code" => "CITY451", "name" => "Empat Lawang", "displayname" => "Empat Lawang", "description" => "Empat Lawang", "numsort" => 4510, "status" => 451, ]); 
        DB::table("city")->insert([ "id" => 452, "code" => "CITY452", "name" => "Lahat", "displayname" => "Lahat", "description" => "Lahat", "numsort" => 4520, "status" => 452, ]); 
        DB::table("city")->insert([ "id" => 453, "code" => "CITY453", "name" => "Lubuk Linggau", "displayname" => "Lubuk Linggau", "description" => "Lubuk Linggau", "numsort" => 4530, "status" => 453, ]); 
        DB::table("city")->insert([ "id" => 454, "code" => "CITY454", "name" => "Muara Enim", "displayname" => "Muara Enim", "description" => "Muara Enim", "numsort" => 4540, "status" => 454, ]); 
        DB::table("city")->insert([ "id" => 455, "code" => "CITY455", "name" => "Musi Banyuasin", "displayname" => "Musi Banyuasin", "description" => "Musi Banyuasin", "numsort" => 4550, "status" => 455, ]); 
        DB::table("city")->insert([ "id" => 456, "code" => "CITY456", "name" => "Musi Rawas", "displayname" => "Musi Rawas", "description" => "Musi Rawas", "numsort" => 4560, "status" => 456, ]); 
        DB::table("city")->insert([ "id" => 457, "code" => "CITY457", "name" => "Ogan Ilir", "displayname" => "Ogan Ilir", "description" => "Ogan Ilir", "numsort" => 4570, "status" => 457, ]); 
        DB::table("city")->insert([ "id" => 458, "code" => "CITY458", "name" => "Ogan Komering Ilir", "displayname" => "Ogan Komering Ilir", "description" => "Ogan Komering Ilir", "numsort" => 4580, "status" => 458, ]); 
        DB::table("city")->insert([ "id" => 459, "code" => "CITY459", "name" => "Ogan Komering Ulu", "displayname" => "Ogan Komering Ulu", "description" => "Ogan Komering Ulu", "numsort" => 4590, "status" => 459, ]); 
        DB::table("city")->insert([ "id" => 460, "code" => "CITY460", "name" => "Ogan Komering Ulu Selatan", "displayname" => "Ogan Komering Ulu Selatan", "description" => "Ogan Komering Ulu Selatan", "numsort" => 4600, "status" => 460, ]); 
        DB::table("city")->insert([ "id" => 461, "code" => "CITY461", "name" => "Ogan Komering Ulu Timur", "displayname" => "Ogan Komering Ulu Timur", "description" => "Ogan Komering Ulu Timur", "numsort" => 4610, "status" => 461, ]); 
        DB::table("city")->insert([ "id" => 462, "code" => "CITY462", "name" => "Pagar Alam", "displayname" => "Pagar Alam", "description" => "Pagar Alam", "numsort" => 4620, "status" => 462, ]); 
        DB::table("city")->insert([ "id" => 463, "code" => "CITY463", "name" => "Palembang", "displayname" => "Palembang", "description" => "Palembang", "numsort" => 4630, "status" => 463, ]); 
        DB::table("city")->insert([ "id" => 464, "code" => "CITY464", "name" => "Prabumulih", "displayname" => "Prabumulih", "description" => "Prabumulih", "numsort" => 4640, "status" => 464, ]); 
        DB::table("city")->insert([ "id" => 465, "code" => "CITY465", "name" => "Asahan", "displayname" => "Asahan", "description" => "Asahan", "numsort" => 4650, "status" => 465, ]); 
        DB::table("city")->insert([ "id" => 466, "code" => "CITY466", "name" => "Batu Bara", "displayname" => "Batu Bara", "description" => "Batu Bara", "numsort" => 4660, "status" => 466, ]); 
        DB::table("city")->insert([ "id" => 467, "code" => "CITY467", "name" => "Binjai", "displayname" => "Binjai", "description" => "Binjai", "numsort" => 4670, "status" => 467, ]); 
        DB::table("city")->insert([ "id" => 468, "code" => "CITY468", "name" => "Dairi", "displayname" => "Dairi", "description" => "Dairi", "numsort" => 4680, "status" => 468, ]); 
        DB::table("city")->insert([ "id" => 469, "code" => "CITY469", "name" => "Deli Serdang", "displayname" => "Deli Serdang", "description" => "Deli Serdang", "numsort" => 4690, "status" => 469, ]); 
        DB::table("city")->insert([ "id" => 470, "code" => "CITY470", "name" => "Gunungsitoli", "displayname" => "Gunungsitoli", "description" => "Gunungsitoli", "numsort" => 4700, "status" => 470, ]); 
        DB::table("city")->insert([ "id" => 471, "code" => "CITY471", "name" => "Humbang Hasundutan", "displayname" => "Humbang Hasundutan", "description" => "Humbang Hasundutan", "numsort" => 4710, "status" => 471, ]); 
        DB::table("city")->insert([ "id" => 472, "code" => "CITY472", "name" => "Karo", "displayname" => "Karo", "description" => "Karo", "numsort" => 4720, "status" => 472, ]); 
        DB::table("city")->insert([ "id" => 473, "code" => "CITY473", "name" => "Labuhan Batu", "displayname" => "Labuhan Batu", "description" => "Labuhan Batu", "numsort" => 4730, "status" => 473, ]); 
        DB::table("city")->insert([ "id" => 474, "code" => "CITY474", "name" => "Labuhan Batu Selatan", "displayname" => "Labuhan Batu Selatan", "description" => "Labuhan Batu Selatan", "numsort" => 4740, "status" => 474, ]); 
        DB::table("city")->insert([ "id" => 475, "code" => "CITY475", "name" => "Labuhan Batu Utara", "displayname" => "Labuhan Batu Utara", "description" => "Labuhan Batu Utara", "numsort" => 4750, "status" => 475, ]); 
        DB::table("city")->insert([ "id" => 476, "code" => "CITY476", "name" => "Langkat", "displayname" => "Langkat", "description" => "Langkat", "numsort" => 4760, "status" => 476, ]); 
        DB::table("city")->insert([ "id" => 477, "code" => "CITY477", "name" => "Mandailing Natal", "displayname" => "Mandailing Natal", "description" => "Mandailing Natal", "numsort" => 4770, "status" => 477, ]); 
        DB::table("city")->insert([ "id" => 478, "code" => "CITY478", "name" => "Medan", "displayname" => "Medan", "description" => "Medan", "numsort" => 4780, "status" => 478, ]); 
        DB::table("city")->insert([ "id" => 479, "code" => "CITY479", "name" => "Nias", "displayname" => "Nias", "description" => "Nias", "numsort" => 4790, "status" => 479, ]); 
        DB::table("city")->insert([ "id" => 480, "code" => "CITY480", "name" => "Nias Barat", "displayname" => "Nias Barat", "description" => "Nias Barat", "numsort" => 4800, "status" => 480, ]); 
        DB::table("city")->insert([ "id" => 481, "code" => "CITY481", "name" => "Nias Selatan", "displayname" => "Nias Selatan", "description" => "Nias Selatan", "numsort" => 4810, "status" => 481, ]); 
        DB::table("city")->insert([ "id" => 482, "code" => "CITY482", "name" => "Nias Utara", "displayname" => "Nias Utara", "description" => "Nias Utara", "numsort" => 4820, "status" => 482, ]); 
        DB::table("city")->insert([ "id" => 483, "code" => "CITY483", "name" => "Padang Lawas", "displayname" => "Padang Lawas", "description" => "Padang Lawas", "numsort" => 4830, "status" => 483, ]); 
        DB::table("city")->insert([ "id" => 484, "code" => "CITY484", "name" => "Padang Lawas Utara", "displayname" => "Padang Lawas Utara", "description" => "Padang Lawas Utara", "numsort" => 4840, "status" => 484, ]); 
        DB::table("city")->insert([ "id" => 485, "code" => "CITY485", "name" => "Padang Sidempuan", "displayname" => "Padang Sidempuan", "description" => "Padang Sidempuan", "numsort" => 4850, "status" => 485, ]); 
        DB::table("city")->insert([ "id" => 486, "code" => "CITY486", "name" => "Pakpak Bharat", "displayname" => "Pakpak Bharat", "description" => "Pakpak Bharat", "numsort" => 4860, "status" => 486, ]); 
        DB::table("city")->insert([ "id" => 487, "code" => "CITY487", "name" => "Pematang Siantar", "displayname" => "Pematang Siantar", "description" => "Pematang Siantar", "numsort" => 4870, "status" => 487, ]); 
        DB::table("city")->insert([ "id" => 488, "code" => "CITY488", "name" => "Samosir", "displayname" => "Samosir", "description" => "Samosir", "numsort" => 4880, "status" => 488, ]); 
        DB::table("city")->insert([ "id" => 489, "code" => "CITY489", "name" => "Serdang Bedagai", "displayname" => "Serdang Bedagai", "description" => "Serdang Bedagai", "numsort" => 4890, "status" => 489, ]); 
        DB::table("city")->insert([ "id" => 490, "code" => "CITY490", "name" => "Sibolga", "displayname" => "Sibolga", "description" => "Sibolga", "numsort" => 4900, "status" => 490, ]); 
        DB::table("city")->insert([ "id" => 491, "code" => "CITY491", "name" => "Simalungun", "displayname" => "Simalungun", "description" => "Simalungun", "numsort" => 4910, "status" => 491, ]); 
        DB::table("city")->insert([ "id" => 492, "code" => "CITY492", "name" => "Tanjung Balai", "displayname" => "Tanjung Balai", "description" => "Tanjung Balai", "numsort" => 4920, "status" => 492, ]); 
        DB::table("city")->insert([ "id" => 493, "code" => "CITY493", "name" => "Tapanuli Selatan", "displayname" => "Tapanuli Selatan", "description" => "Tapanuli Selatan", "numsort" => 4930, "status" => 493, ]); 
        DB::table("city")->insert([ "id" => 494, "code" => "CITY494", "name" => "Tapanuli Tengah", "displayname" => "Tapanuli Tengah", "description" => "Tapanuli Tengah", "numsort" => 4940, "status" => 494, ]); 
        DB::table("city")->insert([ "id" => 495, "code" => "CITY495", "name" => "Tapanuli Utara", "displayname" => "Tapanuli Utara", "description" => "Tapanuli Utara", "numsort" => 4950, "status" => 495, ]); 
        DB::table("city")->insert([ "id" => 496, "code" => "CITY496", "name" => "Tebing Tinggi", "displayname" => "Tebing Tinggi", "description" => "Tebing Tinggi", "numsort" => 4960, "status" => 496, ]); 
        DB::table("city")->insert([ "id" => 497, "code" => "CITY497", "name" => "Toba Samosir", "displayname" => "Toba Samosir", "description" => "Toba Samosir", "numsort" => 4970, "status" => 497, ]); 
        
        
    }
}
